package stdgo._internal.net.textproto;
import stdgo._internal.strings.Strings;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.io.Io;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.testing.Testing;
import stdgo._internal.net.Net;
@:keep @:follow @:using(stdgo._internal.net.textproto.Textproto_t__struct_14pointer_static_extension.T__struct_14Pointer_static_extension) @:using(stdgo._internal.net.textproto.Textproto_t__struct_14pointerpointer_static_extension.T__struct_14PointerPointer_static_extension) typedef T__struct_14PointerPointer = stdgo.Pointer<stdgo._internal.net.textproto.Textproto_t__struct_14pointer.T__struct_14Pointer>;
