package stdgo._internal.net.textproto;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.net.Net;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
@:keep @:follow @:using(stdgo._internal.net.textproto.Textproto_t__struct_21pointerpointer_static_extension.T__struct_21PointerPointer_static_extension) typedef T__struct_21PointerPointerPointer = stdgo.Pointer<stdgo._internal.net.textproto.Textproto_t__struct_21pointerpointer.T__struct_21PointerPointer>;
