package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testExported___localname___934Exported_196082_asInterface) class T_testExported___localname___934Exported_196082_static_extension {

}
