package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_140pointerpointer_static_extension.T__struct_140PointerPointer_static_extension) typedef T__struct_140PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_140pointerpointer.T__struct_140PointerPointer>;
