package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_exampleStructTag_Lookup___localname___S_2238Pointer_asInterface) class T_exampleStructTag_Lookup___localname___S_2238Pointer_static_extension {

}
