package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_67pointerpointer_static_extension.T__struct_67PointerPointer_static_extension) typedef T__struct_67PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_67pointerpointer.T__struct_67PointerPointer>;
