package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_10pointerpointer_static_extension.T__struct_10PointerPointer_static_extension) typedef T__struct_10PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_10pointerpointer.T__struct_10PointerPointer>;
