package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_40pointerpointer_static_extension.T__struct_40PointerPointer_static_extension) typedef T__struct_40PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_40pointerpointer.T__struct_40PointerPointer>;
