package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_exampleValue_FieldByName___localname___user_4433_asInterface) class T_exampleValue_FieldByName___localname___user_4433_static_extension {

}
