package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_32pointerpointer_static_extension.T__struct_32PointerPointer_static_extension) typedef T__struct_32PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_32pointerpointer.T__struct_32PointerPointer>;
