package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_29pointerpointer_static_extension.T__struct_29PointerPointer_static_extension) typedef T__struct_29PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_29pointerpointer.T__struct_29PointerPointer>;
