package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testStructOf___localname___structFieldType_141939Pointer_asInterface) class T_testStructOf___localname___structFieldType_141939Pointer_static_extension {

}
