package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_64pointerpointer_static_extension.T__struct_64PointerPointer_static_extension) typedef T__struct_64PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_64pointerpointer.T__struct_64PointerPointer>;
