package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_63pointerpointer_static_extension.T__struct_63PointerPointer_static_extension) typedef T__struct_63PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_63pointerpointer.T__struct_63PointerPointer>;
