package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_98pointerpointer_static_extension.T__struct_98PointerPointer_static_extension) typedef T__struct_98PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_98pointerpointer.T__struct_98PointerPointer>;
