package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testMakeFuncInvalidReturnAssignments___localname___T_59310Pointer_asInterface) class T_testMakeFuncInvalidReturnAssignments___localname___T_59310Pointer_static_extension {

}
