package _internal.reflect_test;
@:named @:using(_internal.reflect_test.Reflect_test_t_testmapof___localname___v_161202_static_extension.T_testMapOf___localname___V_161202_static_extension) @:using(_internal.reflect_test.Reflect_test_t_testmapof___localname___v_161202_static_extension.T_testMapOf___localname___V_161202_static_extension) typedef T_testMapOf___localname___V_161202 = stdgo.GoFloat64;
