package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testExported___localname___BigP_196136Pointer_asInterface) class T_testExported___localname___BigP_196136Pointer_static_extension {

}
