package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testSwapper___localname___pairPtr_197893Pointer_asInterface) class T_testSwapper___localname___pairPtr_197893Pointer_static_extension {

}
