package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testGCBits___localname___Xbigptrscalar_184657_asInterface) class T_testGCBits___localname___Xbigptrscalar_184657_static_extension {

}
