package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_23pointerpointer_static_extension.T__struct_23PointerPointer_static_extension) typedef T__struct_23PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_23pointerpointer.T__struct_23PointerPointer>;
