package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_80pointerpointer_static_extension.T__struct_80PointerPointer_static_extension) typedef T__struct_80PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_80pointerpointer.T__struct_80PointerPointer>;
