package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_60pointerpointer_static_extension.T__struct_60PointerPointer_static_extension) typedef T__struct_60PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_60pointerpointer.T__struct_60PointerPointer>;
