package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_90pointerpointer_static_extension.T__struct_90PointerPointer_static_extension) typedef T__struct_90PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_90pointerpointer.T__struct_90PointerPointer>;
