package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testGCBits___localname___Scalar_185180Pointer_asInterface) class T_testGCBits___localname___Scalar_185180Pointer_static_extension {

}
