package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testFieldByIndexNil___localname___P_170011Pointer_asInterface) class T_testFieldByIndexNil___localname___P_170011Pointer_static_extension {

}
