package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_21pointerpointer_static_extension.T__struct_21PointerPointer_static_extension) typedef T__struct_21PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_21pointerpointer.T__struct_21PointerPointer>;
