package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testImplicitMapConversion___localname___MyBuffer_2646_asInterface) class T_testImplicitMapConversion___localname___MyBuffer_2646_static_extension {

}
