package _internal.reflect_test;
function testUnaddressableField(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        var _b:stdgo._internal.reflect.Reflect_buffer.Buffer = ({} : stdgo._internal.reflect.Reflect_buffer.Buffer);
        var _localBuffer:_internal.reflect_test.Reflect_test_t__struct_124.T__struct_124 = ({ _buf : (null : stdgo.Slice<stdgo.GoUInt8>) } : _internal.reflect_test.Reflect_test_t__struct_124.T__struct_124);
        var _lv = @:assignType (stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_localBuffer, stdgo._internal.internal.reflect.GoType.refType({ get : () -> stdgo._internal.internal.reflect.GoType.structType([{ name : "_buf", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }) }, optional : false }]) })) : stdgo.Ref<_internal.reflect_test.Reflect_test_t__struct_124.T__struct_124>), stdgo._internal.internal.reflect.GoType.structType([{ name : "_buf", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> stdgo._internal.internal.reflect.GoType.structType([{ name : "_buf", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }) }, optional : false }]) })))).elem()?.__copy__() : stdgo._internal.reflect.Reflect_value.Value);
        var _rv = @:assignType (stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(stdgo.Go.asInterface(_b, _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_bufferdotbuffer.__type__stdgodot_internaldotreflectdotReflect_bufferdotBuffer), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_bufferdotbuffer.__type__stdgodot_internaldotreflectdotReflect_bufferdotBuffer)))?.__copy__() : stdgo._internal.reflect.Reflect_value.Value);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7499"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic(("Set" : stdgo.GoString), function():Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7500"
            _lv.set(_rv?.__copy__());
        });
    }
