package _internal.reflect_test;
function testMethod5(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        var checkF = @:assignType (function(_name:stdgo.GoString, _f:(stdgo.GoInt, stdgo.GoUInt8) -> { var _0 : stdgo.GoUInt8; var _1 : stdgo.GoInt; }, _inc:stdgo.GoInt):Void {
            var __tmp__ = _f((1000 : stdgo.GoInt), (99 : stdgo.GoUInt8)), _b:stdgo.GoUInt8 = __tmp__._0, _x:stdgo.GoInt = __tmp__._1;
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2790"
            if (((_b != (99 : stdgo.GoUInt8)) || (_x != ((1000 : stdgo.GoInt) + _inc : stdgo.GoInt)) : Bool)) {
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2791"
                _t.errorf(("%s(1000, 99) = %v, %v, want 99, %v" : stdgo.GoString), new stdgo.AnyInterface(_name, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(_b, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint8_kind))), new stdgo.AnyInterface(_x, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), new stdgo.AnyInterface(((1000 : stdgo.GoInt) + _inc : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))));
            };
        } : (stdgo.GoString, (stdgo.GoInt, stdgo.GoUInt8) -> { var _0 : stdgo.GoUInt8; var _1 : stdgo.GoInt; }, stdgo.GoInt) -> Void);
        var checkV = @:assignType (function(_name:stdgo.GoString, _i:stdgo._internal.reflect.Reflect_value.Value, _inc:stdgo.GoInt):Void {
            var _bx = _i.method((0 : stdgo.GoInt)).call((new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(2, 2, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((1000 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))))?.__copy__(), stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((99 : stdgo.GoUInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint8_kind))))?.__copy__()].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>));
            var _b = @:assignType (_bx[(0 : stdgo.GoInt)].interface_() : stdgo.AnyInterface);
            var _x = @:assignType (_bx[(1 : stdgo.GoInt)].interface_() : stdgo.AnyInterface);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2799"
            if (((_b != new stdgo.AnyInterface((99 : stdgo.GoUInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint8_kind)))) || (_x != new stdgo.AnyInterface(((1000 : stdgo.GoInt) + _inc : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : Bool)) {
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2800"
                _t.errorf(("direct %s.M(1000, 99) = %v, %v, want 99, %v" : stdgo.GoString), new stdgo.AnyInterface(_name, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), _b, _x, new stdgo.AnyInterface(((1000 : stdgo.GoInt) + _inc : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))));
            };
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2803"
            checkF((_name + (".M" : stdgo.GoString)?.__copy__() : stdgo.GoString)?.__copy__(), (stdgo.Go.typeAssert(_i.method((0 : stdgo.GoInt)).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [stdgo._internal.internal.reflect.GoType.basic(int_kind), stdgo._internal.internal.reflect.GoType.basic(uint8_kind)] }, { get : () -> [stdgo._internal.internal.reflect.GoType.basic(uint8_kind), stdgo._internal.internal.reflect.GoType.basic(int_kind)] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : (stdgo.GoInt, stdgo.GoUInt8) -> { var _0 : stdgo.GoUInt8; var _1 : stdgo.GoInt; }), _inc);
        } : (stdgo.GoString, stdgo._internal.reflect.Reflect_value.Value, stdgo.GoInt) -> Void);
        var tinterType = stdgo._internal.reflect.Reflect_typeof.typeOf(({
            final __t__ = (stdgo.Go.setRef((null : _internal.reflect_test.Reflect_test_tinter.Tinter), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tinterdottinter.__type___internaldotreflect_testdotReflect_test_tinterdotTinter })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tinter.Tinter>);
            if (__t__ == null) {
                new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tinterdottinter.__type___internaldotreflect_testdotReflect_test_tinterdotTinter }))).__setNil__();
            } else {
                new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
            };
        })).elem();
        var checkI = @:assignType (function(_name:stdgo.GoString, _i:stdgo.AnyInterface, _inc:stdgo.GoInt):Void {
            var _v = @:assignType (stdgo._internal.reflect.Reflect_valueof.valueOf(_i)?.__copy__() : stdgo._internal.reflect.Reflect_value.Value);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2810"
            checkV(_name?.__copy__(), _v?.__copy__(), _inc);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2811"
            checkV(((("(i=" : stdgo.GoString) + _name?.__copy__() : stdgo.GoString) + (")" : stdgo.GoString)?.__copy__() : stdgo.GoString)?.__copy__(), _v.convert(tinterType)?.__copy__(), _inc);
        } : (stdgo.GoString, stdgo.AnyInterface, stdgo.GoInt) -> Void);
        var _sv = @:assignType ((1 : _internal.reflect_test.Reflect_test_tsmallv.Tsmallv) : _internal.reflect_test.Reflect_test_tsmallv.Tsmallv);
        var _sv__pointer__ = stdgo.Go.pointer(_sv);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2815"
        checkI(("sv" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_sv, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tsmallvdottsmallv.__type___internaldotreflect_testdotReflect_test_tsmallvdotTsmallv), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tsmallvdottsmallv.__type___internaldotreflect_testdotReflect_test_tsmallvdotTsmallv)), (1 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2816"
        checkI(("&sv" : stdgo.GoString), new stdgo.AnyInterface(_sv__pointer__, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tsmallvdottsmallv.__type___internaldotreflect_testdotReflect_test_tsmallvdotTsmallv }))), (1 : stdgo.GoInt));
        var _sp = @:assignType ((2 : _internal.reflect_test.Reflect_test_tsmallp.Tsmallp) : _internal.reflect_test.Reflect_test_tsmallp.Tsmallp);
        var _sp__pointer__ = stdgo.Go.pointer(_sp);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2819"
        checkI(("&sp" : stdgo.GoString), new stdgo.AnyInterface(_sp__pointer__, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tsmallpdottsmallp.__type___internaldotreflect_testdotReflect_test_tsmallpdotTsmallp }))), (2 : stdgo.GoInt));
        var _wv = @:assignType ((new stdgo.GoUIntptr((new stdgo.GoUIntptr(3) : _internal.reflect_test.Reflect_test_twordv.Twordv)) : _internal.reflect_test.Reflect_test_twordv.Twordv) : _internal.reflect_test.Reflect_test_twordv.Twordv);
        var _wv__pointer__ = stdgo.Go.pointer(_wv);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2822"
        checkI(("wv" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_wv, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_twordvdottwordv.__type___internaldotreflect_testdotReflect_test_twordvdotTwordv), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_twordvdottwordv.__type___internaldotreflect_testdotReflect_test_twordvdotTwordv)), (3 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2823"
        checkI(("&wv" : stdgo.GoString), new stdgo.AnyInterface(_wv__pointer__, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_twordvdottwordv.__type___internaldotreflect_testdotReflect_test_twordvdotTwordv }))), (3 : stdgo.GoInt));
        var _wp = @:assignType ((new stdgo.GoUIntptr((new stdgo.GoUIntptr(4) : _internal.reflect_test.Reflect_test_twordp.Twordp)) : _internal.reflect_test.Reflect_test_twordp.Twordp) : _internal.reflect_test.Reflect_test_twordp.Twordp);
        var _wp__pointer__ = stdgo.Go.pointer(_wp);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2826"
        checkI(("&wp" : stdgo.GoString), new stdgo.AnyInterface(_wp__pointer__, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_twordpdottwordp.__type___internaldotreflect_testdotReflect_test_twordpdotTwordp }))), (4 : stdgo.GoInt));
        var _bv = @:assignType ((new stdgo.GoArray<stdgo.GoUIntptr>(2, 2, ...[(new stdgo.GoUIntptr(5) : stdgo.GoUIntptr), (new stdgo.GoUIntptr(6) : stdgo.GoUIntptr)]) : stdgo.GoArray<stdgo.GoUIntptr>) : _internal.reflect_test.Reflect_test_tbigv.Tbigv);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2829"
        checkI(("bv" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_bv, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigvdottbigv.__type___internaldotreflect_testdotReflect_test_tbigvdotTbigv), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigvdottbigv.__type___internaldotreflect_testdotReflect_test_tbigvdotTbigv)), (11 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2830"
        checkI(("&bv" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_bv, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigvdottbigv.__type___internaldotreflect_testdotReflect_test_tbigvdotTbigv })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tbigv.Tbigv>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigvdottbigv.__type___internaldotreflect_testdotReflect_test_tbigvdotTbigv), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigvdottbigv.__type___internaldotreflect_testdotReflect_test_tbigvdotTbigv }))), (11 : stdgo.GoInt));
        var _bp = @:assignType ((new stdgo.GoArray<stdgo.GoUIntptr>(2, 2, ...[(new stdgo.GoUIntptr(7) : stdgo.GoUIntptr), (new stdgo.GoUIntptr(8) : stdgo.GoUIntptr)]) : stdgo.GoArray<stdgo.GoUIntptr>) : _internal.reflect_test.Reflect_test_tbigp.Tbigp);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2833"
        checkI(("&bp" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_bp, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigpdottbigp.__type___internaldotreflect_testdotReflect_test_tbigpdotTbigp })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tbigp.Tbigp>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigpdottbigp.__type___internaldotreflect_testdotReflect_test_tbigpdotTbigp), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tbigpdottbigp.__type___internaldotreflect_testdotReflect_test_tbigpdotTbigp }))), (15 : stdgo.GoInt));
        var _t4 = @:assignType (new _internal.reflect_test.Reflect_test_tm4.Tm4() : _internal.reflect_test.Reflect_test_tm4.Tm4);
        var _t3 = @:assignType (new _internal.reflect_test.Reflect_test_tm3.Tm3((stdgo.Go.setRef(_t4, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm4dottm4.__type___internaldotreflect_testdotReflect_test_tm4dotTm4 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tm4.Tm4>)) : _internal.reflect_test.Reflect_test_tm3.Tm3);
        var _t2 = @:assignType (new _internal.reflect_test.Reflect_test_tm2.Tm2((stdgo.Go.setRef(_t3, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm3dottm3.__type___internaldotreflect_testdotReflect_test_tm3dotTm3 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tm3.Tm3>)) : _internal.reflect_test.Reflect_test_tm2.Tm2);
        var _t1 = @:assignType (new _internal.reflect_test.Reflect_test_tm1.Tm1(_t2?.__copy__()) : _internal.reflect_test.Reflect_test_tm1.Tm1);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2839"
        checkI(("t4" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_t4, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm4dottm4.__type___internaldotreflect_testdotReflect_test_tm4dotTm4), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm4dottm4.__type___internaldotreflect_testdotReflect_test_tm4dotTm4)), (40 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2840"
        checkI(("&t4" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_t4, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm4dottm4.__type___internaldotreflect_testdotReflect_test_tm4dotTm4 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tm4.Tm4>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm4dottm4.__type___internaldotreflect_testdotReflect_test_tm4dotTm4), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm4dottm4.__type___internaldotreflect_testdotReflect_test_tm4dotTm4 }))), (40 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2841"
        checkI(("t3" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_t3, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm3dottm3.__type___internaldotreflect_testdotReflect_test_tm3dotTm3), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm3dottm3.__type___internaldotreflect_testdotReflect_test_tm3dotTm3)), (40 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2842"
        checkI(("&t3" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_t3, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm3dottm3.__type___internaldotreflect_testdotReflect_test_tm3dotTm3 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tm3.Tm3>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm3dottm3.__type___internaldotreflect_testdotReflect_test_tm3dotTm3), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm3dottm3.__type___internaldotreflect_testdotReflect_test_tm3dotTm3 }))), (40 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2843"
        checkI(("t2" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_t2, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm2dottm2.__type___internaldotreflect_testdotReflect_test_tm2dotTm2), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm2dottm2.__type___internaldotreflect_testdotReflect_test_tm2dotTm2)), (40 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2844"
        checkI(("&t2" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_t2, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm2dottm2.__type___internaldotreflect_testdotReflect_test_tm2dotTm2 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tm2.Tm2>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm2dottm2.__type___internaldotreflect_testdotReflect_test_tm2dotTm2), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm2dottm2.__type___internaldotreflect_testdotReflect_test_tm2dotTm2 }))), (40 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2845"
        checkI(("t1" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_t1, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm1dottm1.__type___internaldotreflect_testdotReflect_test_tm1dotTm1), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm1dottm1.__type___internaldotreflect_testdotReflect_test_tm1dotTm1)), (40 : stdgo.GoInt));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2846"
        checkI(("&t1" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_t1, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm1dottm1.__type___internaldotreflect_testdotReflect_test_tm1dotTm1 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tm1.Tm1>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm1dottm1.__type___internaldotreflect_testdotReflect_test_tm1dotTm1), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tm1dottm1.__type___internaldotreflect_testdotReflect_test_tm1dotTm1 }))), (40 : stdgo.GoInt));
        var _tnil:_internal.reflect_test.Reflect_test_tinter.Tinter = (null : _internal.reflect_test.Reflect_test_tinter.Tinter);
        var _vnil = @:assignType (stdgo._internal.reflect.Reflect_valueof.valueOf(({
            final __t__ = (stdgo.Go.setRef(_tnil, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tinterdottinter.__type___internaldotreflect_testdotReflect_test_tinterdotTinter })) : stdgo.Ref<_internal.reflect_test.Reflect_test_tinter.Tinter>);
            if (__t__ == null) {
                new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_tinterdottinter.__type___internaldotreflect_testdotReflect_test_tinterdotTinter }))).__setNil__();
            } else {
                new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
            };
        })).elem()?.__copy__() : stdgo._internal.reflect.Reflect_value.Value);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2850"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic(("Method" : stdgo.GoString), function():Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2850"
            _vnil.method((0 : stdgo.GoInt));
        });
    }
