package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testCanSetField___localname___embed_10451Pointer_asInterface) class T_testCanSetField___localname___embed_10451Pointer_static_extension {

}
