package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_41pointerpointer_static_extension.T__struct_41PointerPointer_static_extension) typedef T__struct_41PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_41pointerpointer.T__struct_41PointerPointer>;
