package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_154pointerpointer_static_extension.T__struct_154PointerPointer_static_extension) typedef T__struct_154PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_154pointerpointer.T__struct_154PointerPointer>;
