package _internal.reflect_test;
function testIsZero(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1400"
        if ((new stdgo.Slice<_internal.reflect_test.Reflect_test_t__struct_89.T__struct_89>(75, 75, ...[
({ _x : new stdgo.AnyInterface(true, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(false, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int8_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int8_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int16_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int16_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int32_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int32_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0i64 : stdgo.GoInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1i64 : stdgo.GoInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0u32 : stdgo.GoUInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1u32 : stdgo.GoUInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoUInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint8_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoUInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint8_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoUInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint16_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoUInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint16_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0u32 : stdgo.GoUInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint32_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1u32 : stdgo.GoUInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint32_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0i64 : stdgo.GoUInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1i64 : stdgo.GoUInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(((0 : stdgo.GoFloat64) : stdgo.GoFloat32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float32_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(((1.2 : stdgo.GoFloat64) : stdgo.GoFloat32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float32_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoFloat64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1.2 : stdgo.GoFloat64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(0f64, 0f64) : stdgo.GoComplex64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(1.2f64, 0f64) : stdgo.GoComplex64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(0f64, 0f64) : stdgo.GoComplex128), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(1.2f64, 0f64) : stdgo.GoComplex128), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(new stdgo.GoComplex128(stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), (0 : stdgo.GoFloat64)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(new stdgo.GoComplex128((0 : stdgo.GoFloat64), stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64))), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(new stdgo.GoComplex128(stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64))), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoUIntptr((new stdgo.GoUIntptr(0) : stdgo.GoUIntptr)) : stdgo.GoUIntptr), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uintptr_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoUIntptr((new stdgo.GoUIntptr(128) : stdgo.GoUIntptr)) : stdgo.GoUIntptr), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uintptr_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : stdgo._internal.reflect.Reflect_zero.zero(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoString>(5, 5, ...[]).__setString__() : stdgo.GoArray<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, 5))))).interface_(), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoString>(5, 5, ...[]).__setString__() : stdgo.GoArray<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, 5))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoString>(5, 5, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), ("a" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.GoArray<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, 5))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>(1, 1, ...[]) : stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 1))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>(1, 1, ...[stdgo.Go.pointer((0 : stdgo.GoInt))]) : stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 1))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>(3, 3, ...[]) : stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 3))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>(3, 3, ...[(new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>)]) : stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 3))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoUInt8>(4096, 4096, ...[]).__setNumber32__() : stdgo.GoArray<stdgo.GoUInt8>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }, 4096))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoUInt8>(4096, 4096, ...[(1 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.GoArray<stdgo.GoUInt8>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }, 4096))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>(3, 3, ...[].concat([for (i in 0 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, 3))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>(3, 3, ...[(new stdgo._internal.reflect.Reflect_value.Value() : stdgo._internal.reflect.Reflect_value.Value), stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))))?.__copy__(), (new stdgo._internal.reflect.Reflect_value.Value() : stdgo._internal.reflect.Reflect_value.Value)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, 3))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Chan<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.Chan<stdgo.GoString>(0, () -> ("" : stdgo.GoString)) : stdgo.Chan<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo._internal.time.Time_after.after((1i64 : stdgo._internal.time.Time_duration.Duration)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(2, { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldottimedottime_timedottime.__type__stdgodot_internaldottimedotTime_timedotTime }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : () -> Void), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo._internal.reflect.Reflect_new_.new_, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_type_dottype_.__type__stdgodot_internaldotreflectdotReflect_type_dotType_] }, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(stdgo._internal.reflect.Reflect_new_.new_(stdgo._internal.reflect.Reflect_typeof.typeOf(({
            final __t__ = (stdgo.Go.setRef((null : stdgo.Error), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError })) : stdgo.Ref<stdgo.Error>);
            if (__t__ == null) {
                new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError }))).__setNil__();
            } else {
                new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
            };
        })).elem()).elem(), _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue)), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : ({
            final __t__ = stdgo.Go.asInterface(stdgo._internal.strings.Strings_newreader.newReader((stdgo.Go.str() : stdgo.GoString)?.__copy__()), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotstringsdotstrings_readerdotreader.__type__stdgodot_internaldotstringsdotStrings_readerdotReader }));
            if (__t__ == null) {
                new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotiodotio_readerdotreader.__type__stdgodot_internaldotiodotIo_readerdotReader)).__setNil__();
            } else {
                new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
            };
        }), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoString, stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(({
            final x = new stdgo.GoMap.GoStringMap<stdgo.GoString>();
            x.__defaultValue__ = () -> ("" : stdgo.GoString);
            {};
            x;
        } : stdgo.GoMap<stdgo.GoString, stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((({
            final x = new stdgo.GoMap.GoStringMap<stdgo.GoString>();
            x.__defaultValue__ = () -> ("" : stdgo.GoString);
            {};
            x;
        } : stdgo.GoMap<stdgo.GoString, stdgo.GoString>) : stdgo.GoMap<stdgo.GoString, stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Pointer<() -> Void>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType }) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Pointer<stdgo.GoInt>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.pointer((0 : stdgo.GoInt)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Slice<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.Slice<stdgo.GoString>((0 : stdgo.GoInt).toBasic(), 0).__setString__() : stdgo.Slice<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((stdgo.Go.str() : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(("not-zero" : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_.T_() : _internal.reflect_test.Reflect_test_t_.T_), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_)), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_.T_((123 : stdgo.GoInt), (456.75 : stdgo.GoFloat64), ("hello" : stdgo.GoString), stdgo.Go.pointer(_internal.reflect_test.Reflect_test___i.__i)) : _internal.reflect_test.Reflect_test_t_.T_), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_)), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _p : (null : stdgo.Pointer<stdgo.GoInt>) } : _internal.reflect_test.Reflect_test_t__struct_90.T__struct_90), stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _p : stdgo.Go.pointer((0 : stdgo.GoInt)) } : _internal.reflect_test.Reflect_test_t__struct_90.T__struct_90), stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _s : (null : stdgo.Slice<stdgo.GoInt>) } : _internal.reflect_test.Reflect_test_t__struct_91.T__struct_91), stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _s : (new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>) } : _internal.reflect_test.Reflect_test_t__struct_91.T__struct_91), stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ value : ({} : stdgo._internal.reflect.Reflect_value.Value) } : _internal.reflect_test.Reflect_test_t__struct_92.T__struct_92), stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }]))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ value : stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))))?.__copy__() } : _internal.reflect_test.Reflect_test_t__struct_92.T__struct_92), stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }]))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((@:default_value null : stdgo._internal.unsafe.Unsafe.UnsafePointer), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.AnyInterface(stdgo.Go.pointer((0 : stdgo.GoInt)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))) : stdgo._internal.unsafe.Unsafe.UnsafePointer), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89)].concat([for (i in 75 ... (75 > 75 ? 75 : 75 : stdgo.GoInt).toBasic()) ({ _x : (null : stdgo.AnyInterface), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t__struct_89.T__struct_89>) != null) for (_i => _tt in (new stdgo.Slice<_internal.reflect_test.Reflect_test_t__struct_89.T__struct_89>(75, 75, ...[
({ _x : new stdgo.AnyInterface(true, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(false, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int8_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int8_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int16_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int16_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int32_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int32_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0i64 : stdgo.GoInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1i64 : stdgo.GoInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0u32 : stdgo.GoUInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1u32 : stdgo.GoUInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoUInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint8_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoUInt8), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint8_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoUInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint16_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1 : stdgo.GoUInt16), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint16_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0u32 : stdgo.GoUInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint32_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1u32 : stdgo.GoUInt32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint32_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0i64 : stdgo.GoUInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1i64 : stdgo.GoUInt64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uint64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(((0 : stdgo.GoFloat64) : stdgo.GoFloat32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float32_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(((1.2 : stdgo.GoFloat64) : stdgo.GoFloat32), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float32_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((0 : stdgo.GoFloat64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((1.2 : stdgo.GoFloat64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(float64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(0f64, 0f64) : stdgo.GoComplex64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex64_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(1.2f64, 0f64) : stdgo.GoComplex64), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex64_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(0f64, 0f64) : stdgo.GoComplex128), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoComplex128(1.2f64, 0f64) : stdgo.GoComplex128), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(new stdgo.GoComplex128(stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), (0 : stdgo.GoFloat64)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(new stdgo.GoComplex128((0 : stdgo.GoFloat64), stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64))), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(new stdgo.GoComplex128(stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64))), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(complex128_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoUIntptr((new stdgo.GoUIntptr(0) : stdgo.GoUIntptr)) : stdgo.GoUIntptr), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uintptr_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoUIntptr((new stdgo.GoUIntptr(128) : stdgo.GoUIntptr)) : stdgo.GoUIntptr), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(uintptr_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : stdgo._internal.reflect.Reflect_zero.zero(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoString>(5, 5, ...[]).__setString__() : stdgo.GoArray<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, 5))))).interface_(), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoString>(5, 5, ...[]).__setString__() : stdgo.GoArray<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, 5))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoString>(5, 5, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), ("a" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.GoArray<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, 5))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>(1, 1, ...[]) : stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 1))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>(1, 1, ...[stdgo.Go.pointer((0 : stdgo.GoInt))]) : stdgo.GoArray<stdgo.Pointer<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 1))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>(3, 3, ...[]) : stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 3))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>(3, 3, ...[(new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>)]) : stdgo.GoArray<stdgo.Slice<stdgo.GoInt>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, 3))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoUInt8>(4096, 4096, ...[]).__setNumber32__() : stdgo.GoArray<stdgo.GoUInt8>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }, 4096))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoUInt8>(4096, 4096, ...[(1 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.GoArray<stdgo.GoUInt8>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }, 4096))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>(3, 3, ...[].concat([for (i in 0 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, 3))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>(3, 3, ...[(new stdgo._internal.reflect.Reflect_value.Value() : stdgo._internal.reflect.Reflect_value.Value), stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))))?.__copy__(), (new stdgo._internal.reflect.Reflect_value.Value() : stdgo._internal.reflect.Reflect_value.Value)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.GoArray<stdgo._internal.reflect.Reflect_value.Value>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, 3))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Chan<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.Chan<stdgo.GoString>(0, () -> ("" : stdgo.GoString)) : stdgo.Chan<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo._internal.time.Time_after.after((1i64 : stdgo._internal.time.Time_duration.Duration)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(2, { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldottimedottime_timedottime.__type__stdgodot_internaldottimedotTime_timedotTime }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : () -> Void), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo._internal.reflect.Reflect_new_.new_, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_type_dottype_.__type__stdgodot_internaldotreflectdotReflect_type_dotType_] }, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(stdgo._internal.reflect.Reflect_new_.new_(stdgo._internal.reflect.Reflect_typeof.typeOf(({
            final __t__ = (stdgo.Go.setRef((null : stdgo.Error), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError })) : stdgo.Ref<stdgo.Error>);
            if (__t__ == null) {
                new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError }))).__setNil__();
            } else {
                new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
            };
        })).elem()).elem(), _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue)), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : ({
            final __t__ = stdgo.Go.asInterface(stdgo._internal.strings.Strings_newreader.newReader((stdgo.Go.str() : stdgo.GoString)?.__copy__()), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotstringsdotstrings_readerdotreader.__type__stdgodot_internaldotstringsdotStrings_readerdotReader }));
            if (__t__ == null) {
                new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotiodotio_readerdotreader.__type__stdgodot_internaldotiodotIo_readerdotReader)).__setNil__();
            } else {
                new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
            };
        }), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoString, stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(({
            final x = new stdgo.GoMap.GoStringMap<stdgo.GoString>();
            x.__defaultValue__ = () -> ("" : stdgo.GoString);
            {};
            x;
        } : stdgo.GoMap<stdgo.GoString, stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(({
            final x = new stdgo.GoMap.GoStringMap<stdgo.GoString>();
            x.__defaultValue__ = () -> ("" : stdgo.GoString);
            {};
            x;
        } : stdgo.GoMap<stdgo.GoString, stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Pointer<() -> Void>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType }) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Pointer<stdgo.GoInt>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.pointer((0 : stdgo.GoInt)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((null : stdgo.Slice<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.Slice<stdgo.GoString>((0 : stdgo.GoInt).toBasic(), 0).__setString__() : stdgo.Slice<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((stdgo.Go.str() : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(("not-zero" : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_.T_() : _internal.reflect_test.Reflect_test_t_.T_), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_)), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_.T_((123 : stdgo.GoInt), (456.75 : stdgo.GoFloat64), ("hello" : stdgo.GoString), stdgo.Go.pointer(_internal.reflect_test.Reflect_test___i.__i)) : _internal.reflect_test.Reflect_test_t_.T_), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_dott_.__type___internaldotreflect_testdotReflect_test_t_dotT_)), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _p : (null : stdgo.Pointer<stdgo.GoInt>) } : _internal.reflect_test.Reflect_test_t__struct_90.T__struct_90), stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _p : stdgo.Go.pointer((0 : stdgo.GoInt)) } : _internal.reflect_test.Reflect_test_t__struct_90.T__struct_90), stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_p", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _s : (null : stdgo.Slice<stdgo.GoInt>) } : _internal.reflect_test.Reflect_test_t__struct_91.T__struct_91), stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ _s : (new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>) } : _internal.reflect_test.Reflect_test_t__struct_91.T__struct_91), stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_s", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }) }, optional : false }]))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ value : ({} : stdgo._internal.reflect.Reflect_value.Value) } : _internal.reflect_test.Reflect_test_t__struct_92.T__struct_92), stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }]))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface(stdgo.Go.asInterface(({ value : stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))))?.__copy__() } : _internal.reflect_test.Reflect_test_t__struct_92.T__struct_92), stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "value", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue }, optional : false }]))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((@:default_value null : stdgo._internal.unsafe.Unsafe.UnsafePointer), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))), _want : true } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89),
({ _x : new stdgo.AnyInterface((new stdgo.AnyInterface(stdgo.Go.pointer((0 : stdgo.GoInt)), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))) : stdgo._internal.unsafe.Unsafe.UnsafePointer), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89)].concat([for (i in 75 ... (75 > 75 ? 75 : 75 : stdgo.GoInt).toBasic()) ({ _x : (null : stdgo.AnyInterface), _want : false } : _internal.reflect_test.Reflect_test_t__struct_89.T__struct_89)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t__struct_89.T__struct_89>)) {
            var _x:stdgo._internal.reflect.Reflect_value.Value = ({} : stdgo._internal.reflect.Reflect_value.Value);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1493"
            {
                var __tmp__ = @:castTranslate try {
                    { _0 : (stdgo.Go.typeAssert(_tt._x, _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_valuedotvalue.__type__stdgodot_internaldotreflectdotReflect_valuedotValue) : stdgo._internal.reflect.Reflect_value.Value), _1 : true };
                } catch(__exception__) {
                    { _0 : ({} : stdgo._internal.reflect.Reflect_value.Value), _1 : false };
                }, _v = __tmp__._0, _ok = __tmp__._1;
                if (_ok) {
                    _x = _v?.__copy__();
                } else {
                    _x = stdgo._internal.reflect.Reflect_valueof.valueOf(_tt._x)?.__copy__();
                };
            };
            var _b = @:assignType (_x.isZero() : Bool);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1500"
            if (_b != (_tt._want)) {
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1501"
                _t.errorf(("%d: IsZero((%s)(%+v)) = %t, want %t" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), new stdgo.AnyInterface(stdgo.Go.asInterface(_x.kind(), _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_kinddotkind.__type__stdgodot_internaldotreflectdotReflect_kinddotKind), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_kinddotkind.__type__stdgodot_internaldotreflectdotReflect_kinddotKind)), _tt._x, new stdgo.AnyInterface(_b, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))), new stdgo.AnyInterface(_tt._want, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))));
            };
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1504"
            if (!stdgo._internal.reflect.Reflect_zero.zero(stdgo._internal.reflect.Reflect_typeof.typeOf(_tt._x)).isZero()) {
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1505"
                _t.errorf(("%d: IsZero(Zero(TypeOf((%s)(%+v)))) is false" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), new stdgo.AnyInterface(stdgo.Go.asInterface(_x.kind(), _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_kinddotkind.__type__stdgodot_internaldotreflectdotReflect_kinddotKind), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_kinddotkind.__type__stdgodot_internaldotreflectdotReflect_kinddotKind)), _tt._x);
            };
            var _p = @:assignType (stdgo._internal.reflect.Reflect_new_.new_(_x.type()).elem()?.__copy__() : stdgo._internal.reflect.Reflect_value.Value);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1509"
            _p.set(_x?.__copy__());
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1510"
            _p.setZero();
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1511"
            if (!_p.isZero()) {
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1512"
                _t.errorf(("%d: IsZero((%s)(%+v)) is true after SetZero" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), new stdgo.AnyInterface(stdgo.Go.asInterface(_p.kind(), _internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_kinddotkind.__type__stdgodot_internaldotreflectdotReflect_kinddotKind), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodot_internaldotreflectdotreflect_kinddotkind.__type__stdgodot_internaldotreflectdotReflect_kinddotKind)), _tt._x);
            };
        };
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1516"
        ({
            var a = function():Void {
                var __deferstack__:Array<{ var ran : Bool; var f : Void -> Void; }> = [];
                try {
                    {
                        __deferstack__.unshift({ ran : false, f : () -> ({
                            var a = function():Void {
                                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1518"
                                {
                                    var _r = @:assignType ({
                                        final r = stdgo.Go.recover_exception;
                                        stdgo.Go.recover_exception = null;
                                        r;
                                    } : stdgo.AnyInterface);
                                    if (({
                                        final value = _r;
                                        (value == null || (value : Dynamic).__nil__);
                                    })) {
                                        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1519"
                                        _t.error(new stdgo.AnyInterface(("should panic for invalid value" : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
                                    };
                                };
                            };
                            a();
                        }) });
                    };
                    //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1522"
                    (new stdgo._internal.reflect.Reflect_value.Value() : stdgo._internal.reflect.Reflect_value.Value).isZero();
                    {
                        for (defer in __deferstack__) {
                            if (defer.ran) continue;
                            defer.ran = true;
                            defer.f();
                        };
                        if (stdgo.Go.recover_exception != null) {
                            final e = stdgo.Go.recover_exception;
                            stdgo.Go.recover_exception = null;
                            @:throw1 throw e;
                        };
                        return;
                    };
                } catch(__exception__) {
                    {
                        var exe:Dynamic = __exception__.native;
                        if ((exe is haxe.ValueException)) exe = exe.value;
                        if ((exe is stdgo.AnyInterface.AnyInterfaceData) == false) {
                            if (__exception__.message == "__return__") throw "__return__";
                            exe = new stdgo.AnyInterface((__exception__.message : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(17)));
                        };
                        stdgo.Go.recover_exception = exe;
                        {
                            function f() {
                                try {
                                    {
                                        for (defer in __deferstack__) {
                                            if (defer.ran) continue;
                                            defer.ran = true;
                                            defer.f();
                                        };
                                    };
                                } catch(__exception__2) {
                                    var exe:Dynamic = __exception__2.native;
                                    if ((exe is haxe.ValueException)) exe = exe.value;
                                    if (!(exe is stdgo.AnyInterface.AnyInterfaceData)) {
                                        if (__exception__.message == "__return__") throw "__return__";
                                        exe = new stdgo.AnyInterface((__exception__.message : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(17)));
                                    };
                                    stdgo.Go.recover_exception = exe;
                                    f();
                                };
                            };
                            f();
                        };
                        if (stdgo.Go.recover_exception != null) {
                            final e = stdgo.Go.recover_exception;
                            stdgo.Go.recover_exception = null;
                            @:throw3 throw e;
                        };
                        return;
                    };
                };
            };
            a();
        });
    }
