package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testFuncLayout___localname___test_179156Pointer_asInterface) class T_testFuncLayout___localname___test_179156Pointer_static_extension {

}
