package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_105pointerpointer_static_extension.T__struct_105PointerPointer_static_extension) typedef T__struct_105PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_105pointerpointer.T__struct_105PointerPointer>;
