package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testCanSetField___localname___S1_10513Pointer_asInterface) class T_testCanSetField___localname___S1_10513Pointer_static_extension {

}
