package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t_structfield_static_extension.T_structField_static_extension) @:using(_internal.reflect_test.Reflect_test_t_structfieldpointer_static_extension.T_structFieldPointer_static_extension) typedef T_structFieldPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t_structfield.T_structField>;
