package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_11pointerpointer_static_extension.T__struct_11PointerPointer_static_extension) typedef T__struct_11PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_11pointerpointer.T__struct_11PointerPointer>;
