package _internal.reflect_test;
function testStructOfExportRules(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        {};
        {};
        {};
        {};
        var _testPanic = @:assignType (function(_i:stdgo.GoInt, _mustPanic:Bool, _f:() -> Void):Void {
            var __deferstack__:Array<{ var ran : Bool; var f : Void -> Void; }> = [];
            try {
                {
                    __deferstack__.unshift({ ran : false, f : () -> ({
                        var a = function():Void {
                            var _err = @:assignType ({
                                final r = stdgo.Go.recover_exception;
                                stdgo.Go.recover_exception = null;
                                r;
                            } : stdgo.AnyInterface);
                            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5336"
                            if ((({
                                final value = _err;
                                (value == null || (value : Dynamic).__nil__);
                            }) && _mustPanic : Bool)) {
                                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5337"
                                _t.errorf(("test-%d did not panic" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))));
                            };
                            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5339"
                            if ((({
                                final value = _err;
                                (value != null && ((value : Dynamic).__nil__ == null || !(value : Dynamic).__nil__));
                            }) && !_mustPanic : Bool)) {
                                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5340"
                                _t.errorf(("test-%d panicked: %v\n" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), _err);
                            };
                        };
                        a();
                    }) });
                };
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5343"
                _f();
                {
                    for (defer in __deferstack__) {
                        if (defer.ran) continue;
                        defer.ran = true;
                        defer.f();
                    };
                    if (stdgo.Go.recover_exception != null) {
                        final e = stdgo.Go.recover_exception;
                        stdgo.Go.recover_exception = null;
                        @:throw1 throw e;
                    };
                    return;
                };
            } catch(__exception__) {
                {
                    var exe:Dynamic = __exception__.native;
                    if ((exe is haxe.ValueException)) exe = exe.value;
                    if ((exe is stdgo.AnyInterface.AnyInterfaceData) == false) {
                        if (__exception__.message == "__return__") throw "__return__";
                        exe = new stdgo.AnyInterface((__exception__.message : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(17)));
                    };
                    stdgo.Go.recover_exception = exe;
                    {
                        function f() {
                            try {
                                {
                                    for (defer in __deferstack__) {
                                        if (defer.ran) continue;
                                        defer.ran = true;
                                        defer.f();
                                    };
                                };
                            } catch(__exception__2) {
                                var exe:Dynamic = __exception__2.native;
                                if ((exe is haxe.ValueException)) exe = exe.value;
                                if (!(exe is stdgo.AnyInterface.AnyInterfaceData)) {
                                    if (__exception__.message == "__return__") throw "__return__";
                                    exe = new stdgo.AnyInterface((__exception__.message : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(17)));
                                };
                                stdgo.Go.recover_exception = exe;
                                f();
                            };
                        };
                        f();
                    };
                    if (stdgo.Go.recover_exception != null) {
                        final e = stdgo.Go.recover_exception;
                        stdgo.Go.recover_exception = null;
                        @:throw3 throw e;
                    };
                    return;
                };
            };
        } : (stdgo.GoInt, Bool, () -> Void) -> Void);
        var _tests = (new stdgo.Slice<_internal.reflect_test.Reflect_test_t__struct_116.T__struct_116>(28, 28, ...[
({ _field : ({ name : ("S1" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : true, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("S1" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172 })))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : true, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s2" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s2" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190 })))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("Name" : stdgo.GoString), type : (null : stdgo._internal.reflect.Reflect_type_.Type_), pkgPath : (stdgo.Go.str() : stdgo.GoString)?.__copy__() } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172))), pkgPath : (stdgo.Go.str() : stdgo.GoString)?.__copy__() } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("S1" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("S1" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172 })))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s2" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s2" : stdgo.GoString), anonymous : true, type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190 })))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s2" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : false, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s2" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : false, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("S" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : true, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("S" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172 })))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : true, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("S" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : true, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("S" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190 })))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : true, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172 })))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190 })))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : false, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s1_142172.T_testStructOfExportRules___localname___S1_142172>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s1_142172dott_teststructofexportrules___localname___s1_142172.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s1_142172dotT_testStructOfExportRules___localname___S1_142172 })))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : false, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190() : _internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : false, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("s" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_teststructofexportrules___localname___s2_142190.T_testStructOfExportRules___localname___s2_142190>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_teststructofexportrules___localname___s2_142190dott_teststructofexportrules___localname___s2_142190.__type___internaldotreflect_testdotReflect_test_t_teststructofexportrules___localname___s2_142190dotT_testStructOfExportRules___localname___s2_142190 })))), pkgPath : ("other/pkg" : stdgo.GoString) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : false, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t__934type.T__934Type() : _internal.reflect_test.Reflect_test_t__934type.T__934Type), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__934typedott__934type.__type___internaldotreflect_testdotReflect_test_t__934typedotT__934Type), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__934typedott__934type.__type___internaldotreflect_testdotReflect_test_t__934typedotT__934Type))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t__966type.T__966Type() : _internal.reflect_test.Reflect_test_t__966type.T__966Type), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__966typedott__966type.__type___internaldotreflect_testdotReflect_test_t__966typedotT__966Type), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__966typedott__966type.__type___internaldotreflect_testdotReflect_test_t__966typedotT__966Type))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : true, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("Φ" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : true, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116),
({ _field : ({ name : ("φ" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) } : stdgo._internal.reflect.Reflect_structfield.StructField), _exported : false, _mustPanic : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116)].concat([for (i in 28 ... (28 > 28 ? 28 : 28 : stdgo.GoInt).toBasic()) ({ _field : ({} : stdgo._internal.reflect.Reflect_structfield.StructField), _mustPanic : false, _exported : false } : _internal.reflect_test.Reflect_test_t__struct_116.T__struct_116)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t__struct_116.T__struct_116>);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5459"
        if (_tests != null) for (_i => _test in _tests) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5460"
            _testPanic(_i, _test._mustPanic, function():Void {
                var _typ = @:assignType (stdgo._internal.reflect.Reflect_structof.structOf((new stdgo.Slice<stdgo._internal.reflect.Reflect_structfield.StructField>(1, 1, ...[_test._field?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_structfield.StructField)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_structfield.StructField>)) : stdgo._internal.reflect.Reflect_type_.Type_);
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5462"
                if (_typ == null) {
                    //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5463"
                    _t.errorf(("test-%d: error creating struct type" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))));
                    //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5464"
                    return;
                };
                var _field = @:assignType (_typ.field((0 : stdgo.GoInt))?.__copy__() : stdgo._internal.reflect.Reflect_structfield.StructField);
                var _n = @:assignType (_field.name?.__copy__() : stdgo.GoString);
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5468"
                if (_n == ((stdgo.Go.str() : stdgo.GoString))) {
                    //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5469"
                    throw new stdgo.AnyInterface(("field.Name must not be empty" : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind)));
                };
                var _exported = @:assignType (stdgo._internal.go.token.Token_isexported.isExported(_n?.__copy__()) : Bool);
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5472"
                if (_exported != (_test._exported)) {
                    //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5473"
                    _t.errorf(("test-%d: got exported=%v want exported=%v" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), new stdgo.AnyInterface(_exported, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))), new stdgo.AnyInterface(_test._exported, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))));
                };
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5475"
                if (_field.pkgPath != (_test._field.pkgPath)) {
                    //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L5476"
                    _t.errorf(("test-%d: got PkgPath=%q want pkgPath=%q" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), new stdgo.AnyInterface(_field.pkgPath, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(_test._field.pkgPath, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
                };
            });
        };
    }
