package _internal.reflect_test;
@:structInit @:using(_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t_94655_static_extension.T_testSetPanic___localname___T_94655_static_extension) @:using(_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t_94655_static_extension.T_testSetPanic___localname___T_94655_static_extension) class T_testSetPanic___localname___T_94655 {
    public var x : stdgo.GoInt = 0;
    @:embedded
    public var _t1 : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571 = ({} : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571);
    @:embedded
    public var t2 : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606 = ({} : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606);
    public var namedT1 : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571 = ({} : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571);
    public var namedT2 : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606 = ({} : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606);
    public var _namedT1 : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571 = ({} : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571);
    public var _namedT2 : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606 = ({} : _internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606);
    public function new(?x:stdgo.GoInt, ?_t1:_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571, ?t2:_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606, ?namedT1:_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571, ?namedT2:_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606, ?_namedT1:_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t1_94571.T_testSetPanic___localname___t1_94571, ?_namedT2:_internal.reflect_test.Reflect_test_t_testsetpanic___localname___t2_94606.T_testSetPanic___localname___T2_94606) {
        if (x != null) this.x = x;
        if (_t1 != null) this._t1 = _t1;
        if (t2 != null) this.t2 = t2;
        if (namedT1 != null) this.namedT1 = namedT1;
        if (namedT2 != null) this.namedT2 = namedT2;
        if (_namedT1 != null) this._namedT1 = _namedT1;
        if (_namedT2 != null) this._namedT2 = _namedT2;
    }
    public function __underlying__() return new stdgo.AnyInterface(this, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "x", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_t1", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testsetpanic___localname___t1_94571dott_testsetpanic___localname___t1_94571.__type___internaldotreflect_testdotReflect_test_t_testsetpanic___localname___t1_94571dotT_testSetPanic___localname___t1_94571 }, optional : false }, { name : "t2", embedded : true, tag : "", type : { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testsetpanic___localname___t2_94606dott_testsetpanic___localname___t2_94606.__type___internaldotreflect_testdotReflect_test_t_testsetpanic___localname___t2_94606dotT_testSetPanic___localname___T2_94606 }, optional : false }, { name : "namedT1", embedded : false, tag : "", type : { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testsetpanic___localname___t1_94571dott_testsetpanic___localname___t1_94571.__type___internaldotreflect_testdotReflect_test_t_testsetpanic___localname___t1_94571dotT_testSetPanic___localname___t1_94571 }, optional : false }, { name : "namedT2", embedded : false, tag : "", type : { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testsetpanic___localname___t2_94606dott_testsetpanic___localname___t2_94606.__type___internaldotreflect_testdotReflect_test_t_testsetpanic___localname___t2_94606dotT_testSetPanic___localname___T2_94606 }, optional : false }, { name : "_namedT1", embedded : false, tag : "", type : { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testsetpanic___localname___t1_94571dott_testsetpanic___localname___t1_94571.__type___internaldotreflect_testdotReflect_test_t_testsetpanic___localname___t1_94571dotT_testSetPanic___localname___t1_94571 }, optional : false }, { name : "_namedT2", embedded : false, tag : "", type : { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testsetpanic___localname___t2_94606dott_testsetpanic___localname___t2_94606.__type___internaldotreflect_testdotReflect_test_t_testsetpanic___localname___t2_94606dotT_testSetPanic___localname___T2_94606 }, optional : false }])));
    public function __copy__() {
        return new T_testSetPanic___localname___T_94655(x, _t1, t2, namedT1, namedT2, _namedT1, _namedT2);
    }
}
