package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testTypeOfTypeOf___localname___T_192573Pointer_asInterface) class T_testTypeOfTypeOf___localname___T_192573Pointer_static_extension {

}
