package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testCanIntUintFloatComplex___localname___integer_8036Pointer_asInterface) class T_testCanIntUintFloatComplex___localname___integer_8036Pointer_static_extension {

}
