package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testExported___localname___966Unexported_196108_asInterface) class T_testExported___localname___966Unexported_196108_static_extension {

}
