package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_comparablestructpointer_static_extension.ComparableStructPointer_static_extension) typedef ComparableStructPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_comparablestructpointer.ComparableStructPointer>;
