package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_130pointerpointer_static_extension.T__struct_130PointerPointer_static_extension) typedef T__struct_130PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_130pointerpointer.T__struct_130PointerPointer>;
