package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_73pointerpointer_static_extension.T__struct_73PointerPointer_static_extension) typedef T__struct_73PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_73pointerpointer.T__struct_73PointerPointer>;
