package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_43pointerpointer_static_extension.T__struct_43PointerPointer_static_extension) typedef T__struct_43PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_43pointerpointer.T__struct_43PointerPointer>;
