package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_byteschansend_static_extension.BytesChanSend_static_extension) @:using(_internal.reflect_test.Reflect_test_byteschansendpointer_static_extension.BytesChanSendPointer_static_extension) typedef BytesChanSendPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_byteschansend.BytesChanSend>;
