package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_6pointerpointer_static_extension.T__struct_6PointerPointer_static_extension) typedef T__struct_6PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_6pointerpointer.T__struct_6PointerPointer>;
