package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testArrayOf___localname___Tstring_130432Pointer_asInterface) class T_testArrayOf___localname___Tstring_130432Pointer_static_extension {

}
