package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testAlignment___localname___T2inner_32363Pointer_asInterface) class T_testAlignment___localname___T2inner_32363Pointer_static_extension {

}
