package _internal.reflect_test;
function testBytes(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3705"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic(("on int Value" : stdgo.GoString), function():Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3705"
            stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))).bytes();
        });
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3706"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic(("of non-byte slice" : stdgo.GoString), function():Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3706"
            stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) })))).bytes();
        });
        {};
        var _x = @:assignType (new stdgo.Slice<stdgo.GoUInt8>(4, 4, ...[(1 : stdgo.GoUInt8), (2 : stdgo.GoUInt8), (3 : stdgo.GoUInt8), (4 : stdgo.GoUInt8)]).__setNumber32__() : _internal.reflect_test.Reflect_test_t_testbytes___localname___s_91498.T_testBytes___localname___S_91498);
        var _y = stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(_x, new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___s_91498dott_testbytes___localname___s_91498.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___s_91498dotT_testBytes___localname___S_91498))).bytes();
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3711"
        if (!stdgo._internal.bytes.Bytes_equal.equal(_x, _y)) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3712"
            _t.fatalf(("ValueOf(%v).Bytes() = %v" : stdgo.GoString), new stdgo.AnyInterface(_x, new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___s_91498dott_testbytes___localname___s_91498.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___s_91498dotT_testBytes___localname___S_91498)), new stdgo.AnyInterface(_y, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }))));
        };
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3714"
        if (stdgo.Go.pointer(_x[(0 : stdgo.GoInt)]) != (stdgo.Go.pointer(_y[(0 : stdgo.GoInt)]))) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3715"
            _t.errorf(("ValueOf(%p).Bytes() = %p" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_x[(0 : stdgo.GoInt)]), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }))), new stdgo.AnyInterface(stdgo.Go.pointer(_y[(0 : stdgo.GoInt)]), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }))));
        };
        {};
        var _a = @:assignType ((new stdgo.GoArray<stdgo.GoUInt8>(4, 4, ...[(1 : stdgo.GoUInt8), (2 : stdgo.GoUInt8), (3 : stdgo.GoUInt8), (4 : stdgo.GoUInt8)]).__setNumber32__() : _internal.reflect_test.Reflect_test_t_testbytes___localname___a_91709.T_testBytes___localname___A_91709)?.__copy__() : _internal.reflect_test.Reflect_test_t_testbytes___localname___a_91709.T_testBytes___localname___A_91709);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3720"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic(("unaddressable" : stdgo.GoString), function():Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3720"
            stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(_a, new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___a_91709dott_testbytes___localname___a_91709.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___a_91709dotT_testBytes___localname___A_91709))).bytes();
        });
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3721"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic(("on ptr Value" : stdgo.GoString), function():Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3721"
            stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((stdgo.Go.setRef(_a, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___a_91709dott_testbytes___localname___a_91709.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___a_91709dotT_testBytes___localname___A_91709 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_t_testbytes___localname___a_91709.T_testBytes___localname___A_91709>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___a_91709dott_testbytes___localname___a_91709.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___a_91709dotT_testBytes___localname___A_91709 })))).bytes();
        });
        var _b = stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((stdgo.Go.setRef(_a, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___a_91709dott_testbytes___localname___a_91709.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___a_91709dotT_testBytes___localname___A_91709 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_t_testbytes___localname___a_91709.T_testBytes___localname___A_91709>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___a_91709dott_testbytes___localname___a_91709.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___a_91709dotT_testBytes___localname___A_91709 })))).elem().bytes();
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3723"
        if (!stdgo._internal.bytes.Bytes_equal.equal((_a.__slice__(0) : stdgo.Slice<stdgo.GoUInt8>), _y)) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3724"
            _t.fatalf(("ValueOf(%v).Bytes() = %v" : stdgo.GoString), new stdgo.AnyInterface(_a, new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___a_91709dott_testbytes___localname___a_91709.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___a_91709dotT_testBytes___localname___A_91709)), new stdgo.AnyInterface(_b, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }))));
        };
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3726"
        if (stdgo.Go.pointer(_a[(0 : stdgo.GoInt)]) != (stdgo.Go.pointer(_b[(0 : stdgo.GoInt)]))) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3727"
            _t.errorf(("ValueOf(%p).Bytes() = %p" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_a[(0 : stdgo.GoInt)]), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }))), new stdgo.AnyInterface(stdgo.Go.pointer(_b[(0 : stdgo.GoInt)]), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }))));
        };
        {};
        {};
        {};
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3735"
        stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201>(4, 4, ...[(1 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201), (2 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201), (3 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201), (4 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201)]).__setNumber32__() : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___b_92201dott_testbytes___localname___b_92201.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___b_92201dotT_testBytes___localname___B_92201 })))).bytes();
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3736"
        stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((stdgo.Go.setRef(new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201>(4, 4).__setNumber32__(), stdgo._internal.internal.reflect.GoType.refType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___b_92201dott_testbytes___localname___b_92201.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___b_92201dotT_testBytes___localname___B_92201 }, 4) })) : stdgo.Ref<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___b_92201dott_testbytes___localname___b_92201.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___b_92201dotT_testBytes___localname___B_92201 }, 4) })))).elem().bytes();
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3737"
        stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201>(4, 4, ...[(1 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201), (2 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201), (3 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201), (4 : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201)]).__setNumber32__() : _internal.reflect_test.Reflect_test_t_testbytes___localname___sb_92214.T_testBytes___localname___SB_92214), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___sb_92214dott_testbytes___localname___sb_92214.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___sb_92214dotT_testBytes___localname___SB_92214))).bytes();
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L3738"
        stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((stdgo.Go.setRef(new _internal.reflect_test.Reflect_test_t_testbytes___localname___ab_92227.T_testBytes___localname___AB_92227(4, 4, ...[for (i in 0 ... 4) ((0 : stdgo.GoUInt8) : _internal.reflect_test.Reflect_test_t_testbytes___localname___b_92201.T_testBytes___localname___B_92201)]), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___ab_92227dott_testbytes___localname___ab_92227.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___ab_92227dotT_testBytes___localname___AB_92227 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_t_testbytes___localname___ab_92227.T_testBytes___localname___AB_92227>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testbytes___localname___ab_92227dott_testbytes___localname___ab_92227.__type___internaldotreflect_testdotReflect_test_t_testbytes___localname___ab_92227dotT_testBytes___localname___AB_92227 })))).elem().bytes();
    }
