package _internal.reflect_test;
function testMakeFuncValidReturnAssignments(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        var _f:() -> stdgo.Error = null;
        _f = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_f, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2309"
            return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(({
                final __t__ = stdgo._internal.io.Io_eof.eOF;
                if (__t__ == null) {
                    new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError)).__setNil__();
                } else {
                    new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
                };
            }))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
        }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> stdgo.Error);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2311"
        _f();
        var _g:() -> stdgo._internal.io.Io_writer.Writer = null;
        _g = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_g, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotiodotio_writerdotwriter.__type__stdgodot_internaldotiodotIo_writerdotWriter] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
            var _w:stdgo._internal.io.Io_writecloser.WriteCloser = stdgo.Go.asInterface((stdgo.Go.setRef((new _internal.reflect_test.Reflect_test_wc.WC() : _internal.reflect_test.Reflect_test_wc.WC), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_wcdotwc.__type___internaldotreflect_testdotReflect_test_wcdotWC })) : stdgo.Ref<_internal.reflect_test.Reflect_test_wc.WC>), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_wcdotwc.__type___internaldotreflect_testdotReflect_test_wcdotWC }));
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2317"
            return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(({
                final __t__ = (stdgo.Go.setRef(_w, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotiodotio_writecloserdotwritecloser.__type__stdgodot_internaldotiodotIo_writecloserdotWriteCloser })) : stdgo.Ref<stdgo._internal.io.Io_writecloser.WriteCloser>);
                if (__t__ == null) {
                    new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotiodotio_writecloserdotwritecloser.__type__stdgodot_internaldotiodotIo_writecloserdotWriteCloser }))).__setNil__();
                } else {
                    new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
                };
            })).elem()?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
        }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotiodotio_writerdotwriter.__type__stdgodot_internaldotiodotIo_writerdotWriter] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> stdgo._internal.io.Io_writer.Writer);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2319"
        _g();
        var _h:() -> stdgo.Chan<stdgo.GoInt> = null;
        _h = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_h, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [stdgo._internal.internal.reflect.GoType.chanType(2, { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) })] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2324"
            return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((new stdgo.Chan<stdgo.GoInt>(0, () -> (0 : stdgo.GoInt)) : stdgo.Chan<stdgo.GoInt>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }))))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
        }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) })] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> stdgo.Chan<stdgo.GoInt>);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2326"
        _h();
        {};
        var _i:() -> _internal.reflect_test.Reflect_test_t_testmakefuncvalidreturnassignments___localname___t_58184.T_testMakeFuncValidReturnAssignments___localname___T_58184 = null;
        _i = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmakefuncvalidreturnassignments___localname___t_58184dott_testmakefuncvalidreturnassignments___localname___t_58184.__type___internaldotreflect_testdotReflect_test_t_testmakefuncvalidreturnassignments___localname___t_58184dotT_testMakeFuncValidReturnAssignments___localname___T_58184] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2332"
            return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(stdgo.Go.asInterface(({ _a : (1 : stdgo.GoInt), _b : (2 : stdgo.GoInt), _c : (3 : stdgo.GoInt) } : _internal.reflect_test.Reflect_test_t__struct_95.T__struct_95), stdgo._internal.internal.reflect.GoType.structType([{ name : "_a", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_b", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_c", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_a", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_b", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_c", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }]))))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
        }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmakefuncvalidreturnassignments___localname___t_58184dott_testmakefuncvalidreturnassignments___localname___t_58184.__type___internaldotreflect_testdotReflect_test_t_testmakefuncvalidreturnassignments___localname___t_58184dotT_testMakeFuncValidReturnAssignments___localname___T_58184] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> _internal.reflect_test.Reflect_test_t_testmakefuncvalidreturnassignments___localname___t_58184.T_testMakeFuncValidReturnAssignments___localname___T_58184);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2334"
        _i();
    }
