package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_115pointerpointer_static_extension.T__struct_115PointerPointer_static_extension) typedef T__struct_115PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_115pointerpointer.T__struct_115PointerPointer>;
