package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testArrayOfDirectIface___localname___T_135295_asInterface) class T_testArrayOfDirectIface___localname___T_135295_static_extension {

}
