package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_129pointerpointer_static_extension.T__struct_129PointerPointer_static_extension) typedef T__struct_129PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_129pointerpointer.T__struct_129PointerPointer>;
