package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_62pointerpointer_static_extension.T__struct_62PointerPointer_static_extension) typedef T__struct_62PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_62pointerpointer.T__struct_62PointerPointer>;
