package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_148pointerpointer_static_extension.T__struct_148PointerPointer_static_extension) typedef T__struct_148PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_148pointerpointer.T__struct_148PointerPointer>;
