package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_126pointerpointer_static_extension.T__struct_126PointerPointer_static_extension) typedef T__struct_126PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_126pointerpointer.T__struct_126PointerPointer>;
