package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_settablestruct_static_extension.SettableStruct_static_extension) @:using(_internal.reflect_test.Reflect_test_settablestructpointer_static_extension.SettableStructPointer_static_extension) typedef SettableStructPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_settablestruct.SettableStruct>;
