package _internal.reflect_test;
function testMapOf(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        {};
        {};
        var _v = @:assignType (stdgo._internal.reflect.Reflect_makemap.makeMap(stdgo._internal.reflect.Reflect_mapof.mapOf(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((stdgo.Go.str() : _internal.reflect_test.Reflect_test_t_testmapof___localname___k_161187.T_testMapOf___localname___K_161187), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___k_161187dott_testmapof___localname___k_161187.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___k_161187dotT_testMapOf___localname___K_161187))), stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(((0 : stdgo.GoFloat64) : _internal.reflect_test.Reflect_test_t_testmapof___localname___v_161202.T_testMapOf___localname___V_161202), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___v_161202dott_testmapof___localname___v_161202.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___v_161202dotT_testMapOf___localname___V_161202)))))?.__copy__() : stdgo._internal.reflect.Reflect_value.Value);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6142"
        stdgo._internal.runtime.Runtime_gc.gC();
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6143"
        _v.setMapIndex(stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((("a" : stdgo.GoString) : _internal.reflect_test.Reflect_test_t_testmapof___localname___k_161187.T_testMapOf___localname___K_161187), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___k_161187dott_testmapof___localname___k_161187.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___k_161187dotT_testMapOf___localname___K_161187)))?.__copy__(), stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(((1 : stdgo.GoFloat64) : _internal.reflect_test.Reflect_test_t_testmapof___localname___v_161202.T_testMapOf___localname___V_161202), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___v_161202dott_testmapof___localname___v_161202.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___v_161202dotT_testMapOf___localname___V_161202)))?.__copy__());
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6144"
        stdgo._internal.runtime.Runtime_gc.gC();
        var _s = @:assignType (stdgo._internal.fmt.Fmt_sprint.sprint(_v.interface_())?.__copy__() : stdgo.GoString);
        var _want = @:assignType (("map[a:1]" : stdgo.GoString) : stdgo.GoString);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6148"
        if (_s != (_want)) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6149"
            _t.errorf(("constructed map = %s, want %s" : stdgo.GoString), new stdgo.AnyInterface(_s, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(_want, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
        };
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6153"
        _internal.reflect_test.Reflect_test__checksametype._checkSameType(_t, stdgo._internal.reflect.Reflect_mapof.mapOf(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(((0 : stdgo.GoFloat64) : _internal.reflect_test.Reflect_test_t_testmapof___localname___v_161202.T_testMapOf___localname___V_161202), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___v_161202dott_testmapof___localname___v_161202.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___v_161202dotT_testMapOf___localname___V_161202))), stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((stdgo.Go.str() : _internal.reflect_test.Reflect_test_t_testmapof___localname___k_161187.T_testMapOf___localname___K_161187), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___k_161187dott_testmapof___localname___k_161187.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___k_161187dotT_testMapOf___localname___K_161187)))), new stdgo.AnyInterface((null : stdgo.GoMap<_internal.reflect_test.Reflect_test_t_testmapof___localname___v_161202.T_testMapOf___localname___V_161202, _internal.reflect_test.Reflect_test_t_testmapof___localname___k_161187.T_testMapOf___localname___K_161187>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___v_161202dott_testmapof___localname___v_161202.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___v_161202dotT_testMapOf___localname___V_161202 }, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmapof___localname___k_161187dott_testmapof___localname___k_161187.__type___internaldotreflect_testdotReflect_test_t_testmapof___localname___k_161187dotT_testMapOf___localname___K_161187 }))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6156"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic(("invalid key type" : stdgo.GoString), function():Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6156"
            stdgo._internal.reflect.Reflect_mapof.mapOf(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((null : () -> Void), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(false, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind)))));
        });
    }
