package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_99pointerpointer_static_extension.T__struct_99PointerPointer_static_extension) typedef T__struct_99PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_99pointerpointer.T__struct_99PointerPointer>;
