package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_mybytesarrayptrpointer_static_extension.MyBytesArrayPtrPointer_static_extension) typedef MyBytesArrayPtrPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_mybytesarrayptrpointer.MyBytesArrayPtrPointer>;
