package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_unexportedfirstpointer_static_extension.UnExportedFirstPointer_static_extension) typedef UnExportedFirstPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_unexportedfirstpointer.UnExportedFirstPointer>;
