package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testFieldByIndexErr___localname___B_5184Pointer_asInterface) class T_testFieldByIndexErr___localname___B_5184Pointer_static_extension {

}
