package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_mybytesarray0pointer_static_extension.MyBytesArray0Pointer_static_extension) typedef MyBytesArray0PointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_mybytesarray0pointer.MyBytesArray0Pointer>;
