package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_117pointerpointer_static_extension.T__struct_117PointerPointer_static_extension) typedef T__struct_117PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_117pointerpointer.T__struct_117PointerPointer>;
