package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_135pointerpointer_static_extension.T__struct_135PointerPointer_static_extension) typedef T__struct_135PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_135pointerpointer.T__struct_135PointerPointer>;
