package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t_structwithselfptrpointer_static_extension.T_structWithSelfPtrPointer_static_extension) typedef T_structWithSelfPtrPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t_structwithselfptrpointer.T_structWithSelfPtrPointer>;
