package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_139pointerpointer_static_extension.T__struct_139PointerPointer_static_extension) typedef T__struct_139PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_139pointerpointer.T__struct_139PointerPointer>;
