package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_65pointerpointer_static_extension.T__struct_65PointerPointer_static_extension) typedef T__struct_65PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_65pointerpointer.T__struct_65PointerPointer>;
