package _internal.reflect_test;
function testExported(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        {};
        {};
        {};
        {};
        {};
        {};
        {};
        {};
        var _exportTests = (new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198>(12, 12, ...[
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_d1.D1() : _internal.reflect_test.Reflect_test_d1.D1), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_d1dotd1.__type___internaldotreflect_testdotReflect_test_d1dotD1), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_d1dotd1.__type___internaldotreflect_testdotReflect_test_d1dotD1)), true) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_d1.D1>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_d1dotd1.__type___internaldotreflect_testdotReflect_test_d1dotD1), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_d1dotd1.__type___internaldotreflect_testdotReflect_test_d1dotD1 }))), true) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_big.T_big() : _internal.reflect_test.Reflect_test_t_big.T_big), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_bigdott_big.__type___internaldotreflect_testdotReflect_test_t_bigdotT_big), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_bigdott_big.__type___internaldotreflect_testdotReflect_test_t_bigdotT_big)), false) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface(stdgo.Go.asInterface((null : stdgo.Ref<_internal.reflect_test.Reflect_test_t_big.T_big>), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_bigdott_big.__type___internaldotreflect_testdotReflect_test_t_bigdotT_big), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_bigdott_big.__type___internaldotreflect_testdotReflect_test_t_bigdotT_big }))), false) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface(stdgo.Go.asInterface((null : _internal.reflect_test.Reflect_test_t_testexported___localname___bigp_196136.T_testExported___localname___BigP_196136), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testexported___localname___bigp_196136dott_testexported___localname___bigp_196136.__type___internaldotreflect_testdotReflect_test_t_testexported___localname___bigp_196136dotT_testExported___localname___BigP_196136), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testexported___localname___bigp_196136dott_testexported___localname___bigp_196136.__type___internaldotreflect_testdotReflect_test_t_testexported___localname___bigp_196136dotT_testExported___localname___BigP_196136)), true) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface((null : stdgo.Pointer<_internal.reflect_test.Reflect_test_t_testexported___localname___bigp_196136.T_testExported___localname___BigP_196136>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testexported___localname___bigp_196136dott_testexported___localname___bigp_196136.__type___internaldotreflect_testdotReflect_test_t_testexported___localname___bigp_196136dotT_testExported___localname___BigP_196136 }))), true) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t__934exported.T__934Exported() : _internal.reflect_test.Reflect_test_t__934exported.T__934Exported), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__934exporteddott__934exported.__type___internaldotreflect_testdotReflect_test_t__934exporteddotT__934Exported), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__934exporteddott__934exported.__type___internaldotreflect_testdotReflect_test_t__934exporteddotT__934Exported)), true) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t__966unexported.T__966Unexported() : _internal.reflect_test.Reflect_test_t__966unexported.T__966Unexported), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__966unexporteddott__966unexported.__type___internaldotreflect_testdotReflect_test_t__966unexporteddotT__966Unexported), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t__966unexporteddott__966unexported.__type___internaldotreflect_testdotReflect_test_t__966unexporteddotT__966Unexported)), false) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface((0 : _internal.reflect_test.Reflect_test_t_testexported___localname___p_196152.T_testExported___localname___P_196152), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testexported___localname___p_196152dott_testexported___localname___p_196152.__type___internaldotreflect_testdotReflect_test_t_testexported___localname___p_196152dotT_testExported___localname___P_196152)), true) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface((null : _internal.reflect_test.Reflect_test_t_testexported___localname___p_196164.T_testExported___localname___p_196164), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testexported___localname___p_196164dott_testexported___localname___p_196164.__type___internaldotreflect_testdotReflect_test_t_testexported___localname___p_196164dotT_testExported___localname___p_196164)), false) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface((null : _internal.reflect_test.Reflect_test_t_testexported___localname___p2_196175.T_testExported___localname___P2_196175), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testexported___localname___p2_196175dott_testexported___localname___p2_196175.__type___internaldotreflect_testdotReflect_test_t_testexported___localname___p2_196175dotT_testExported___localname___P2_196175)), true) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198),
(new _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198(new stdgo.AnyInterface((null : _internal.reflect_test.Reflect_test_t_testexported___localname___p3_196186.T_testExported___localname___p3_196186), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testexported___localname___p3_196186dott_testexported___localname___p3_196186.__type___internaldotreflect_testdotReflect_test_t_testexported___localname___p3_196186dotT_testExported___localname___p3_196186)), false) : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198)].concat([for (i in 12 ... (12 > 12 ? 12 : 12 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testexported___localname___exporttest_196198.T_testExported___localname___exportTest_196198>);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7357"
        if (_exportTests != null) for (_i => _test in _exportTests) {
            var _typ = @:assignType (stdgo._internal.reflect.Reflect_typeof.typeOf(_test._v) : stdgo._internal.reflect.Reflect_type_.Type_);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7359"
            {
                var _got = @:assignType (stdgo._internal.reflect.Reflect_isexported.isExported(_typ) : Bool);
                if (_got != (_test._want)) {
                    //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7360"
                    _t.errorf(("%d: %s exported=%v, want %v" : stdgo.GoString), new stdgo.AnyInterface(_i, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))), new stdgo.AnyInterface(_typ.name(), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(_got, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))), new stdgo.AnyInterface(_test._want, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(bool_kind))));
                };
            };
        };
    }
