package _internal.reflect_test;
function testGCBits(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7038"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((null : stdgo.Pointer<stdgo.GoUInt8>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) })))), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(1 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>));
        {};
        {};
        {};
        {};
        {};
        var tscalar:stdgo._internal.reflect.Reflect_type_.Type_ = (null : stdgo._internal.reflect.Reflect_type_.Type_), tint64:stdgo._internal.reflect.Reflect_type_.Type_ = (null : stdgo._internal.reflect.Reflect_type_.Type_), tptr:stdgo._internal.reflect.Reflect_type_.Type_ = (null : stdgo._internal.reflect.Reflect_type_.Type_), tscalarptr:stdgo._internal.reflect.Reflect_type_.Type_ = (null : stdgo._internal.reflect.Reflect_type_.Type_), tptrscalar:stdgo._internal.reflect.Reflect_type_.Type_ = (null : stdgo._internal.reflect.Reflect_type_.Type_), tbigptrscalar:stdgo._internal.reflect.Reflect_type_.Type_ = (null : stdgo._internal.reflect.Reflect_type_.Type_);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7059"
        {
            {};
            {};
            {};
            {};
            {};
            {};
            tscalar = stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___scalar_185180.T_testGCBits___localname___Scalar_185180() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___scalar_185180.T_testGCBits___localname___Scalar_185180), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___scalar_185180dott_testgcbits___localname___scalar_185180.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___scalar_185180dotT_testGCBits___localname___Scalar_185180), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___scalar_185180dott_testgcbits___localname___scalar_185180.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___scalar_185180dotT_testGCBits___localname___Scalar_185180)));
            tint64 = stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((0i64 : _internal.reflect_test.Reflect_test_t_testgcbits___localname___int64_185410.T_testGCBits___localname___Int64_185410), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___int64_185410dott_testgcbits___localname___int64_185410.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___int64_185410dotT_testGCBits___localname___Int64_185410)));
            tptr = stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___ptr_185214.T_testGCBits___localname___Ptr_185214() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___ptr_185214.T_testGCBits___localname___Ptr_185214), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___ptr_185214dott_testgcbits___localname___ptr_185214.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___ptr_185214dotT_testGCBits___localname___Ptr_185214), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___ptr_185214dott_testgcbits___localname___ptr_185214.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___ptr_185214dotT_testGCBits___localname___Ptr_185214)));
            tscalarptr = stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___scalarptr_185293.T_testGCBits___localname___Scalarptr_185293() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___scalarptr_185293.T_testGCBits___localname___Scalarptr_185293), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___scalarptr_185293dott_testgcbits___localname___scalarptr_185293.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___scalarptr_185293dotT_testGCBits___localname___Scalarptr_185293), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___scalarptr_185293dott_testgcbits___localname___scalarptr_185293.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___scalarptr_185293dotT_testGCBits___localname___Scalarptr_185293)));
            tptrscalar = stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___ptrscalar_185243.T_testGCBits___localname___Ptrscalar_185243() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___ptrscalar_185243.T_testGCBits___localname___Ptrscalar_185243), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___ptrscalar_185243dott_testgcbits___localname___ptrscalar_185243.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___ptrscalar_185243dotT_testGCBits___localname___Ptrscalar_185243), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___ptrscalar_185243dott_testgcbits___localname___ptrscalar_185243.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___ptrscalar_185243dotT_testGCBits___localname___Ptrscalar_185243)));
            tbigptrscalar = stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___bigptrscalar_185343.T_testGCBits___localname___Bigptrscalar_185343() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___bigptrscalar_185343.T_testGCBits___localname___Bigptrscalar_185343), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___bigptrscalar_185343dott_testgcbits___localname___bigptrscalar_185343.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___bigptrscalar_185343dotT_testGCBits___localname___Bigptrscalar_185343), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___bigptrscalar_185343dott_testgcbits___localname___bigptrscalar_185343.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___bigptrscalar_185343dotT_testGCBits___localname___Bigptrscalar_185343)));
        };
        var _empty = (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7092"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500))), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7093"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, tscalar, _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7094"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7095"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, tptr, _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7096"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610))), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7097"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, tscalarptr, _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7098"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(stdgo.Go.asInterface((new _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563() : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7099"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, tptrscalar, _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7101"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 }, 0)))), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7102"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((0 : stdgo.GoInt), tptr), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7103"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(1, 1, ...[].concat([for (i in 0 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 1)))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7104"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((1 : stdgo.GoInt), tptrscalar), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7105"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>(2, 2, ...[].concat([for (i in 0 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }, 2)))), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7106"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((2 : stdgo.GoInt), tscalar), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7107"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>(10000, 10000, ...[].concat([for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }, 10000)))), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7108"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tscalar), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7109"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>(2, 2, ...[].concat([for (i in 0 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 }, 2)))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7110"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((2 : stdgo.GoInt), tptr), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7111"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>(10000, 10000, ...[].concat([for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 }, 10000)))), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7112"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tptr), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7113"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>(2, 2, ...[].concat([for (i in 0 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 2)))), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7114"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((2 : stdgo.GoInt), tscalarptr), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7115"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>(10000, 10000, ...[].concat([for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 10000)))), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7116"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tscalarptr), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7117"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(2, 2, ...[].concat([for (i in 0 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 2)))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7118"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((2 : stdgo.GoInt), tptrscalar), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7119"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(10000, 10000, ...[].concat([for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 10000)))), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7120"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tptrscalar), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7121"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>(1, 1, ...[].concat([for (i in 0 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(10000, 10000, ...[for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])])) : stdgo.GoArray<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 10000) }, 1)))), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7122"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((1 : stdgo.GoInt), stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tptrscalar)), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7123"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>(2, 2, ...[].concat([for (i in 0 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(10000, 10000, ...[for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])])) : stdgo.GoArray<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 10000) }, 2)))), _internal.reflect_test.Reflect_test__rep._rep((20000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7124"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((2 : stdgo.GoInt), stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tptrscalar)), _internal.reflect_test.Reflect_test__rep._rep((20000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7125"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xbigptrscalar_184657.T_testGCBits___localname___Xbigptrscalar_184657>(4, 4, ...[].concat([for (i in 0 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xbigptrscalar_184657.T_testGCBits___localname___Xbigptrscalar_184657)])) : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xbigptrscalar_184657.T_testGCBits___localname___Xbigptrscalar_184657>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xbigptrscalar_184657dott_testgcbits___localname___xbigptrscalar_184657.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xbigptrscalar_184657dotT_testGCBits___localname___Xbigptrscalar_184657 }, 4)))), _internal.reflect_test.Reflect_test__join._join(_internal.reflect_test.Reflect_test__rep._rep((3 : stdgo.GoInt), _internal.reflect_test.Reflect_test__join._join(_internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8))))), _internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7126"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((4 : stdgo.GoInt), tbigptrscalar), _internal.reflect_test.Reflect_test__join._join(_internal.reflect_test.Reflect_test__rep._rep((3 : stdgo.GoInt), _internal.reflect_test.Reflect_test__join._join(_internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8))))), _internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7128"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 })))), (0 : stdgo.GoInt), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7129"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tptr), (0 : stdgo.GoInt), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7130"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 })))), (1 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7131"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tptrscalar), (1 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7132"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 })))), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7133"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tscalar), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7134"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 })))), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7135"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tscalar), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7136"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 })))), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7137"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tptr), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7138"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 })))), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7139"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tptr), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7140"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 })))), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7141"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tscalarptr), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7142"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 })))), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7143"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tscalarptr), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7144"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 })))), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7145"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tptrscalar), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7146"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 })))), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7147"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tptrscalar), (10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7148"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(10000, 10000, ...[for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])])) : stdgo.Slice<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 10000) })))), (1 : stdgo.GoInt), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7149"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tptrscalar)), (1 : stdgo.GoInt), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7150"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>(10000, 10000, ...[for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563)])])) : stdgo.Slice<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 10000) })))), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7151"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tptrscalar)), (2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__rep._rep((10000 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7152"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xbigptrscalar_184657.T_testGCBits___localname___Xbigptrscalar_184657>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xbigptrscalar_184657.T_testGCBits___localname___Xbigptrscalar_184657)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xbigptrscalar_184657.T_testGCBits___localname___Xbigptrscalar_184657>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xbigptrscalar_184657dott_testgcbits___localname___xbigptrscalar_184657.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xbigptrscalar_184657dotT_testGCBits___localname___Xbigptrscalar_184657 })))), (4 : stdgo.GoInt), _internal.reflect_test.Reflect_test__join._join(_internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8)))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7153"
        _internal.reflect_test.Reflect_test__verifygcbitsslice._verifyGCBitsSlice(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(tbigptrscalar), (4 : stdgo.GoInt), _internal.reflect_test.Reflect_test__join._join(_internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((100 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8)))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7155"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((null : stdgo.Chan<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }, 100) })))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7156"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_chanof.chanOf((3 : stdgo._internal.reflect.Reflect_chandir.ChanDir), stdgo._internal.reflect.Reflect_arrayof.arrayOf((100 : stdgo.GoInt), tscalar)), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7158"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((null : stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610> -> Void), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 10000)] }, { get : () -> [] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7159"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_funcof.funcOf((new stdgo.Slice<stdgo._internal.reflect.Reflect_type_.Type_>(1, 1, ...[stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tscalarptr)]) : stdgo.Slice<stdgo._internal.reflect.Reflect_type_.Type_>), (null : stdgo.Slice<stdgo._internal.reflect.Reflect_type_.Type_>), false), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7161"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 10000) }, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 })))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7162"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_mapof.mapOf(stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tscalarptr), tscalar), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7164"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((new stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>(10000, 10000, ...[for (i in 0 ... (10000 > 10000 ? 10000 : 10000 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500)]).__setNil__() : stdgo.Ref<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }, 10000) })))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7165"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_pointerto.pointerTo(stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tscalar)), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7167"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((null : stdgo.Slice<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.sliceType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }, 10000) })))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7168"
        _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_sliceof.sliceOf(stdgo._internal.reflect.Reflect_arrayof.arrayOf((10000 : stdgo.GoInt), tscalar)), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8)));
        var _hdr = (new stdgo.Slice<stdgo.GoUInt8>((2 : stdgo.GoInt).toBasic(), 0).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>);
        var _verifyMapBucket = function(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>, _k:stdgo._internal.reflect.Reflect_type_.Type_, _e:stdgo._internal.reflect.Reflect_type_.Type_, _m:stdgo.AnyInterface, _want:stdgo.Slice<stdgo.GoUInt8>):Void {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7173"
            _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_mapbucketof.mapBucketOf(_k, _e), _want);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7174"
            _internal.reflect_test.Reflect_test__verifygcbits._verifyGCBits(_t, stdgo._internal.reflect.Reflect_cachedbucketof.cachedBucketOf(stdgo._internal.reflect.Reflect_typeof.typeOf(_m)), _want);
        };
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7176"
        _verifyMapBucket(_t, tscalar, tptr, new stdgo.AnyInterface((({
            final x:stdgo.GoMap.GoObjectMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534> = null;
            cast x;
        } : stdgo.GoMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>) : stdgo.GoMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7180"
        _verifyMapBucket(_t, tscalarptr, tptr, new stdgo.AnyInterface((({
            final x:stdgo.GoMap.GoObjectMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534> = null;
            cast x;
        } : stdgo.GoMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>) : stdgo.GoMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7184"
        _verifyMapBucket(_t, tint64, tptr, new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoInt64, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xptr_184534.T_testGCBits___localname___Xptr_184534>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int64_kind) }, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptr_184534dott_testgcbits___localname___xptr_184534.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptr_184534dotT_testGCBits___localname___Xptr_184534 }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__rep._rep((2 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8)))), _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7187"
        _verifyMapBucket(_t, tscalar, tscalar, new stdgo.AnyInterface((({
            final x:stdgo.GoMap.GoObjectMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500> = null;
            cast x;
        } : stdgo.GoMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>) : stdgo.GoMap<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500, _internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalar_184500.T_testGCBits___localname___Xscalar_184500>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalar_184500dott_testgcbits___localname___xscalar_184500.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalar_184500dotT_testGCBits___localname___Xscalar_184500 }))), _empty);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7191"
        _verifyMapBucket(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((2 : stdgo.GoInt), tscalarptr), stdgo._internal.reflect.Reflect_arrayof.arrayOf((3 : stdgo.GoInt), tptrscalar), new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>, stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 2) }, { get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 3) }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((16 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((24 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7195"
        _verifyMapBucket(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((16 : stdgo.GoInt), tscalarptr), stdgo._internal.reflect.Reflect_arrayof.arrayOf((16 : stdgo.GoInt), tptrscalar), new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>, stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 16) }, { get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 16) }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((128 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((128 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7199"
        _verifyMapBucket(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((17 : stdgo.GoInt), tscalarptr), stdgo._internal.reflect.Reflect_arrayof.arrayOf((16 : stdgo.GoInt), tptrscalar), new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>, stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 17) }, { get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 16) }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((128 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8), (0 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7203"
        _verifyMapBucket(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((16 : stdgo.GoInt), tscalarptr), stdgo._internal.reflect.Reflect_arrayof.arrayOf((17 : stdgo.GoInt), tptrscalar), new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>, stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 16) }, { get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 17) }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((128 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((0 : stdgo.GoUInt8), (1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L7207"
        _verifyMapBucket(_t, stdgo._internal.reflect.Reflect_arrayof.arrayOf((17 : stdgo.GoInt), tscalarptr), stdgo._internal.reflect.Reflect_arrayof.arrayOf((17 : stdgo.GoInt), tptrscalar), new stdgo.AnyInterface((null : stdgo.GoMap<stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xscalarptr_184610.T_testGCBits___localname___Xscalarptr_184610>, stdgo.GoArray<_internal.reflect_test.Reflect_test_t_testgcbits___localname___xptrscalar_184563.T_testGCBits___localname___Xptrscalar_184563>>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.mapType({ get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xscalarptr_184610dott_testgcbits___localname___xscalarptr_184610.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xscalarptr_184610dotT_testGCBits___localname___Xscalarptr_184610 }, 17) }, { get : () -> stdgo._internal.internal.reflect.GoType.arrayType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testgcbits___localname___xptrscalar_184563dott_testgcbits___localname___xptrscalar_184563.__type___internaldotreflect_testdotReflect_test_t_testgcbits___localname___xptrscalar_184563dotT_testGCBits___localname___Xptrscalar_184563 }, 17) }))), _internal.reflect_test.Reflect_test__join._join(_hdr, _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__rep._rep((8 : stdgo.GoInt), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))), _internal.reflect_test.Reflect_test__lit._lit((1 : stdgo.GoUInt8))));
    }
