package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_47pointerpointer_static_extension.T__struct_47PointerPointer_static_extension) typedef T__struct_47PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_47pointerpointer.T__struct_47PointerPointer>;
