package _internal.reflect_test;
function testMakeFuncInvalidReturnAssignments(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2339"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic((stdgo.Go.str() : stdgo.GoString)?.__copy__(), function():Void {
            var _f:() -> stdgo.Error = null;
            _f = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_f, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2342"
                return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface((7 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind))))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
            }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodoterror.__type__stdgodotError] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> stdgo.Error);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2344"
            _f();
        });
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2347"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic((stdgo.Go.str() : stdgo.GoString)?.__copy__(), function():Void {
            var _f:() -> stdgo._internal.io.Io_readwritecloser.ReadWriteCloser = null;
            _f = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_f, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotiodotio_readwritecloserdotreadwritecloser.__type__stdgodot_internaldotiodotIo_readwritecloserdotReadWriteCloser] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
                var _w:stdgo._internal.io.Io_writecloser.WriteCloser = stdgo.Go.asInterface((stdgo.Go.setRef((new _internal.reflect_test.Reflect_test_wc.WC() : _internal.reflect_test.Reflect_test_wc.WC), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_wcdotwc.__type___internaldotreflect_testdotReflect_test_wcdotWC })) : stdgo.Ref<_internal.reflect_test.Reflect_test_wc.WC>), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_wcdotwc.__type___internaldotreflect_testdotReflect_test_wcdotWC }));
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2351"
                return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(({
                    final __t__ = (stdgo.Go.setRef(_w, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotiodotio_writecloserdotwritecloser.__type__stdgodot_internaldotiodotIo_writecloserdotWriteCloser })) : stdgo.Ref<stdgo._internal.io.Io_writecloser.WriteCloser>);
                    if (__t__ == null) {
                        new stdgo.AnyInterface(null, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotiodotio_writecloserdotwritecloser.__type__stdgodot_internaldotiodotIo_writecloserdotWriteCloser }))).__setNil__();
                    } else {
                        new stdgo.AnyInterface(__t__, __t__.__underlying__().type);
                    };
                })).elem()?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
            }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type__stdgodot_internaldotiodotio_readwritecloserdotreadwritecloser.__type__stdgodot_internaldotiodotIo_readwritecloserdotReadWriteCloser] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> stdgo._internal.io.Io_readwritecloser.ReadWriteCloser);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2353"
            _f();
        });
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2356"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic((stdgo.Go.str() : stdgo.GoString)?.__copy__(), function():Void {
            var _f:() -> stdgo.Chan<stdgo.GoInt> = null;
            _f = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_f, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) })] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
                var _c:stdgo.Chan<stdgo.GoInt> = (new stdgo.Chan<stdgo.GoInt>(0, () -> (0 : stdgo.GoInt)) : stdgo.Chan<stdgo.GoInt>);
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2360"
                return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(_c, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(2, { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }))))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
            }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [stdgo._internal.internal.reflect.GoType.chanType(0, { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) })] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> stdgo.Chan<stdgo.GoInt>);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2362"
            _f();
        });
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2365"
        _internal.reflect_test.Reflect_test__shouldpanic._shouldPanic((stdgo.Go.str() : stdgo.GoString)?.__copy__(), function():Void {
            {};
            {};
            var _f:() -> _internal.reflect_test.Reflect_test_t_testmakefuncinvalidreturnassignments___localname___t_59310.T_testMakeFuncInvalidReturnAssignments___localname___T_59310 = null;
            _f = (stdgo.Go.typeAssert(stdgo._internal.reflect.Reflect_makefunc.makeFunc(stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface(_f, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmakefuncinvalidreturnassignments___localname___t_59310dott_testmakefuncinvalidreturnassignments___localname___t_59310.__type___internaldotreflect_testdotReflect_test_t_testmakefuncinvalidreturnassignments___localname___t_59310dotT_testMakeFuncInvalidReturnAssignments___localname___T_59310] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })))), function(_0:stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>):stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value> {
                //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2370"
                return (new stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>(1, 1, ...[stdgo._internal.reflect.Reflect_valueof.valueOf(new stdgo.AnyInterface(stdgo.Go.asInterface(({ _a : (1 : stdgo.GoInt), _b : (2 : stdgo.GoInt), _c : (3 : stdgo.GoInt) } : _internal.reflect_test.Reflect_test_t_testmakefuncinvalidreturnassignments___localname___u_59341.T_testMakeFuncInvalidReturnAssignments___localname___U_59341), _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmakefuncinvalidreturnassignments___localname___u_59341dott_testmakefuncinvalidreturnassignments___localname___u_59341.__type___internaldotreflect_testdotReflect_test_t_testmakefuncinvalidreturnassignments___localname___u_59341dotT_testMakeFuncInvalidReturnAssignments___localname___U_59341), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmakefuncinvalidreturnassignments___localname___u_59341dott_testmakefuncinvalidreturnassignments___localname___u_59341.__type___internaldotreflect_testdotReflect_test_t_testmakefuncinvalidreturnassignments___localname___u_59341dotT_testMakeFuncInvalidReturnAssignments___localname___U_59341)))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.reflect.Reflect_value.Value)])) : stdgo.Slice<stdgo._internal.reflect.Reflect_value.Value>);
            }).interface_(), stdgo._internal.internal.reflect.GoType.signature(false, { get : () -> [] }, { get : () -> [_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testmakefuncinvalidreturnassignments___localname___t_59310dott_testmakefuncinvalidreturnassignments___localname___t_59310.__type___internaldotreflect_testdotReflect_test_t_testmakefuncinvalidreturnassignments___localname___t_59310dotT_testMakeFuncInvalidReturnAssignments___localname___T_59310] }, { get : () -> stdgo._internal.internal.reflect.GoType.invalidType })) : () -> _internal.reflect_test.Reflect_test_t_testmakefuncinvalidreturnassignments___localname___t_59310.T_testMakeFuncInvalidReturnAssignments___localname___T_59310);
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L2372"
            _f();
        });
    }
