package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_byteschanrecvpointer_static_extension.BytesChanRecvPointer_static_extension) typedef BytesChanRecvPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_byteschanrecvpointer.BytesChanRecvPointer>;
