package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testStructOfDirectIface___localname___T_150402_asInterface) class T_testStructOfDirectIface___localname___T_150402_static_extension {

}
