package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_109pointerpointer_static_extension.T__struct_109PointerPointer_static_extension) typedef T__struct_109PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_109pointerpointer.T__struct_109PointerPointer>;
