package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_104pointerpointer_static_extension.T__struct_104PointerPointer_static_extension) typedef T__struct_104PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_104pointerpointer.T__struct_104PointerPointer>;
