package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_120pointerpointer_static_extension.T__struct_120PointerPointer_static_extension) typedef T__struct_120PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_120pointerpointer.T__struct_120PointerPointer>;
