package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_92pointerpointer_static_extension.T__struct_92PointerPointer_static_extension) typedef T__struct_92PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_92pointerpointer.T__struct_92PointerPointer>;
