package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testArrayOf___localname___Tstruct_131171Pointer_asInterface) class T_testArrayOf___localname___Tstruct_131171Pointer_static_extension {

}
