package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_84pointerpointer_static_extension.T__struct_84PointerPointer_static_extension) typedef T__struct_84PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_84pointerpointer.T__struct_84PointerPointer>;
