package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_byteschanrecv_static_extension.BytesChanRecv_static_extension) @:using(_internal.reflect_test.Reflect_test_byteschanrecvpointer_static_extension.BytesChanRecvPointer_static_extension) typedef BytesChanRecvPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_byteschanrecv.BytesChanRecv>;
