package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_93pointerpointer_static_extension.T__struct_93PointerPointer_static_extension) typedef T__struct_93PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_93pointerpointer.T__struct_93PointerPointer>;
