package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_132pointerpointer_static_extension.T__struct_132PointerPointer_static_extension) typedef T__struct_132PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_132pointerpointer.T__struct_132PointerPointer>;
