package _internal.reflect_test;
@:keep @:allow(_internal.reflect_test.Reflect_test.T_testArrayOf___localname___Tstruct_131395Pointer_asInterface) class T_testArrayOf___localname___Tstruct_131395Pointer_static_extension {

}
