package _internal.reflect_test;
function testAlignment(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        {};
        {};
        {};
        {};
        var _x = @:assignType (new _internal.reflect_test.Reflect_test_t_testalignment___localname___t1_32324.T_testAlignment___localname___T1_32324((new _internal.reflect_test.Reflect_test_t_testalignment___localname___t1inner_32290.T_testAlignment___localname___T1inner_32290((2 : stdgo.GoInt)) : _internal.reflect_test.Reflect_test_t_testalignment___localname___t1inner_32290.T_testAlignment___localname___T1inner_32290), (17 : stdgo.GoInt)) : _internal.reflect_test.Reflect_test_t_testalignment___localname___t1_32324.T_testAlignment___localname___T1_32324);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1317"
        _internal.reflect_test.Reflect_test__check2ndfield._check2ndField(new stdgo.AnyInterface(stdgo.Go.asInterface(_x, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testalignment___localname___t1_32324dott_testalignment___localname___t1_32324.__type___internaldotreflect_testdotReflect_test_t_testalignment___localname___t1_32324dotT_testAlignment___localname___T1_32324), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testalignment___localname___t1_32324dott_testalignment___localname___t1_32324.__type___internaldotreflect_testdotReflect_test_t_testalignment___localname___t1_32324dotT_testAlignment___localname___T1_32324)), ((new stdgo.GoUIntptr((new stdgo.AnyInterface(stdgo.Go.pointer(_x._f), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))) : stdgo._internal.unsafe.Unsafe.UnsafePointer)) : stdgo.GoUIntptr) - (new stdgo.GoUIntptr((new stdgo.AnyInterface((stdgo.Go.setRef(_x, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testalignment___localname___t1_32324dott_testalignment___localname___t1_32324.__type___internaldotreflect_testdotReflect_test_t_testalignment___localname___t1_32324dotT_testAlignment___localname___T1_32324 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_t_testalignment___localname___t1_32324.T_testAlignment___localname___T1_32324>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))) : stdgo._internal.unsafe.Unsafe.UnsafePointer)) : stdgo.GoUIntptr) : stdgo.GoUIntptr), _t);
        var _x1 = @:assignType (new _internal.reflect_test.Reflect_test_t_testalignment___localname___t2_32400.T_testAlignment___localname___T2_32400((new _internal.reflect_test.Reflect_test_t_testalignment___localname___t2inner_32363.T_testAlignment___localname___T2inner_32363((2 : stdgo.GoInt), (3 : stdgo.GoInt)) : _internal.reflect_test.Reflect_test_t_testalignment___localname___t2inner_32363.T_testAlignment___localname___T2inner_32363), (17 : stdgo.GoInt)) : _internal.reflect_test.Reflect_test_t_testalignment___localname___t2_32400.T_testAlignment___localname___T2_32400);
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L1320"
        _internal.reflect_test.Reflect_test__check2ndfield._check2ndField(new stdgo.AnyInterface(stdgo.Go.asInterface(_x1, _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testalignment___localname___t2_32400dott_testalignment___localname___t2_32400.__type___internaldotreflect_testdotReflect_test_t_testalignment___localname___t2_32400dotT_testAlignment___localname___T2_32400), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testalignment___localname___t2_32400dott_testalignment___localname___t2_32400.__type___internaldotreflect_testdotReflect_test_t_testalignment___localname___t2_32400dotT_testAlignment___localname___T2_32400)), ((new stdgo.GoUIntptr((new stdgo.AnyInterface(stdgo.Go.pointer(_x1._f), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))) : stdgo._internal.unsafe.Unsafe.UnsafePointer)) : stdgo.GoUIntptr) - (new stdgo.GoUIntptr((new stdgo.AnyInterface((stdgo.Go.setRef(_x1, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testalignment___localname___t2_32400dott_testalignment___localname___t2_32400.__type___internaldotreflect_testdotReflect_test_t_testalignment___localname___t2_32400dotT_testAlignment___localname___T2_32400 })) : stdgo.Ref<_internal.reflect_test.Reflect_test_t_testalignment___localname___t2_32400.T_testAlignment___localname___T2_32400>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(unsafepointer_kind))) : stdgo._internal.unsafe.Unsafe.UnsafePointer)) : stdgo.GoUIntptr) : stdgo.GoUIntptr), _t);
    }
