package _internal.reflect_test;
@:keep @:follow @:using(_internal.reflect_test.Reflect_test_t__struct_89pointerpointer_static_extension.T__struct_89PointerPointer_static_extension) typedef T__struct_89PointerPointerPointer = stdgo.Pointer<_internal.reflect_test.Reflect_test_t__struct_89pointerpointer.T__struct_89PointerPointer>;
