package _internal.reflect_test;
@:local @:using(_internal.reflect_test.Reflect_test_t__struct_115_static_extension.T__struct_115_static_extension) @:using(_internal.reflect_test.Reflect_test_t__struct_115_static_extension.T__struct_115_static_extension) @:using(_internal.reflect_test.Reflect_test_t__struct_115_static_extension.T__struct_115_static_extension) typedef T__struct_115 = {
    public var f : _internal.reflect_test.Reflect_test_t_teststructof___localname___structfieldtype_141939.T_testStructOf___localname___structFieldType_141939;
};
