package _internal.reflect_test;
function testChanOfDir(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        {};
        var _crt = @:assignType (stdgo._internal.reflect.Reflect_chanof.chanOf((1 : stdgo._internal.reflect.Reflect_chandir.ChanDir), stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((stdgo.Go.str() : _internal.reflect_test.Reflect_test_t_testchanofdir___localname___t_159545.T_testChanOfDir___localname___T_159545), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testchanofdir___localname___t_159545dott_testchanofdir___localname___t_159545.__type___internaldotreflect_testdotReflect_test_t_testchanofdir___localname___t_159545dotT_testChanOfDir___localname___T_159545)))) : stdgo._internal.reflect.Reflect_type_.Type_);
        var _cst = @:assignType (stdgo._internal.reflect.Reflect_chanof.chanOf((2 : stdgo._internal.reflect.Reflect_chandir.ChanDir), stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((stdgo.Go.str() : _internal.reflect_test.Reflect_test_t_testchanofdir___localname___t_159545.T_testChanOfDir___localname___T_159545), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testchanofdir___localname___t_159545dott_testchanofdir___localname___t_159545.__type___internaldotreflect_testdotReflect_test_t_testchanofdir___localname___t_159545dotT_testChanOfDir___localname___T_159545)))) : stdgo._internal.reflect.Reflect_type_.Type_);
        {};
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6076"
        _internal.reflect_test.Reflect_test__checksametype._checkSameType(_t, stdgo._internal.reflect.Reflect_chanof.chanOf((1 : stdgo._internal.reflect.Reflect_chandir.ChanDir), stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((1 : _internal.reflect_test.Reflect_test_t_testchanofdir___localname___t1_159686.T_testChanOfDir___localname___T1_159686), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testchanofdir___localname___t1_159686dott_testchanofdir___localname___t1_159686.__type___internaldotreflect_testdotReflect_test_t_testchanofdir___localname___t1_159686dotT_testChanOfDir___localname___T1_159686)))), new stdgo.AnyInterface((null : stdgo.Chan<_internal.reflect_test.Reflect_test_t_testchanofdir___localname___t1_159686.T_testChanOfDir___localname___T1_159686>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(2, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testchanofdir___localname___t1_159686dott_testchanofdir___localname___t1_159686.__type___internaldotreflect_testdotReflect_test_t_testchanofdir___localname___t1_159686dotT_testChanOfDir___localname___T1_159686 }))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6077"
        _internal.reflect_test.Reflect_test__checksametype._checkSameType(_t, stdgo._internal.reflect.Reflect_chanof.chanOf((2 : stdgo._internal.reflect.Reflect_chandir.ChanDir), stdgo._internal.reflect.Reflect_typeof.typeOf(new stdgo.AnyInterface((1 : _internal.reflect_test.Reflect_test_t_testchanofdir___localname___t1_159686.T_testChanOfDir___localname___T1_159686), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testchanofdir___localname___t1_159686dott_testchanofdir___localname___t1_159686.__type___internaldotreflect_testdotReflect_test_t_testchanofdir___localname___t1_159686dotT_testChanOfDir___localname___T1_159686)))), new stdgo.AnyInterface((null : stdgo.Chan<_internal.reflect_test.Reflect_test_t_testchanofdir___localname___t1_159686.T_testChanOfDir___localname___T1_159686>), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.chanType(1, { get : () -> _internal.gotype.Gotype___type___internaldotreflect_testdotreflect_test_t_testchanofdir___localname___t1_159686dott_testchanofdir___localname___t1_159686.__type___internaldotreflect_testdotReflect_test_t_testchanofdir___localname___t1_159686dotT_testChanOfDir___localname___T1_159686 }))));
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6080"
        if ((_crt.chanDir().string() : stdgo.GoString) != (("<-chan" : stdgo.GoString))) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6081"
            _t.errorf(("chan dir: have %q, want %q" : stdgo.GoString), new stdgo.AnyInterface((_crt.chanDir().string() : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(("<-chan" : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
        };
        //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6083"
        if ((_cst.chanDir().string() : stdgo.GoString) != (("chan<-" : stdgo.GoString))) {
            //"file:///Users/o/.go/go1.21.3/src/reflect/all_test.go#L6084"
            _t.errorf(("chan dir: have %q, want %q" : stdgo.GoString), new stdgo.AnyInterface((_cst.chanDir().string() : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(("chan<-" : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
        };
    }
