package stdgo._internal.fmt;
import stdgo._internal.errors.Errors;
import stdgo._internal.sort.Sort;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.os.Os;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.io.Io;
import stdgo._internal.internal.fmtsort.Fmtsort;
import stdgo._internal.math.Math;
@:keep @:follow @:using(stdgo._internal.fmt.Fmt_t_stringreader_static_extension.T_stringReader_static_extension) @:using(stdgo._internal.fmt.Fmt_t_stringreaderpointer_static_extension.T_stringReaderPointer_static_extension) typedef T_stringReaderPointer = stdgo.Pointer<stdgo._internal.fmt.Fmt_t_stringreader.T_stringReader>;
