package _internal.githubdotcom.dlclark.regexp2.syntax;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.strings.Strings;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.os.Os;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.sort.Sort;
@:keep @:follow @:using(_internal.githubdotcom.dlclark.regexp2.syntax.Syntax_t_lcmap_static_extension.T_lcMap_static_extension) @:using(_internal.githubdotcom.dlclark.regexp2.syntax.Syntax_t_lcmappointer_static_extension.T_lcMapPointer_static_extension) typedef T_lcMapPointer = stdgo.Pointer<_internal.githubdotcom.dlclark.regexp2.syntax.Syntax_t_lcmap.T_lcMap>;
