package _internal.githubdotcom.dlclark.regexp2.syntax;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.strings.Strings;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.os.Os;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.sort.Sort;
@:keep @:follow @:using(_internal.githubdotcom.dlclark.regexp2.syntax.Syntax_instop_static_extension.InstOp_static_extension) @:using(_internal.githubdotcom.dlclark.regexp2.syntax.Syntax_instoppointer_static_extension.InstOpPointer_static_extension) typedef InstOpPointer = stdgo.Pointer<_internal.githubdotcom.dlclark.regexp2.syntax.Syntax_instop.InstOp>;
