package stdgo._internal.go.scanner;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.path.filepath.Filepath;
import stdgo._internal.go.token.Token;
import stdgo._internal.sort.Sort;
@:named @:using(stdgo._internal.go.scanner.Scanner_errorhandler_static_extension.ErrorHandler_static_extension) @:using(stdgo._internal.go.scanner.Scanner_errorhandler_static_extension.ErrorHandler_static_extension) typedef ErrorHandler = (stdgo._internal.go.token.Token_position.Position, stdgo.GoString) -> Void;
