package stdgo._internal.encoding.json;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.unicode.utf16.Utf16;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.base64.Base64;
import stdgo._internal.strings.Strings;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.sort.Sort;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.io.Io;
import stdgo._internal.math.Math;
import stdgo._internal.errors.Errors;
@:keep @:follow @:using(stdgo._internal.encoding.json.Json_unsupportedtypeerror_static_extension.UnsupportedTypeError_static_extension) @:using(stdgo._internal.encoding.json.Json_unsupportedtypeerrorpointer_static_extension.UnsupportedTypeErrorPointer_static_extension) typedef UnsupportedTypeErrorPointer = stdgo.Pointer<stdgo._internal.encoding.json.Json_unsupportedtypeerror.UnsupportedTypeError>;
