package stdgo._internal.testing;
@:keep @:follow @:using(stdgo._internal.testing.Testing_t__struct_144pointerpointer_static_extension.T__struct_144PointerPointer_static_extension) typedef T__struct_144PointerPointerPointer = stdgo.Pointer<stdgo._internal.testing.Testing_t__struct_144pointerpointer.T__struct_144PointerPointer>;
