package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t__struct_148pointerpointer_static_extension.T__struct_148PointerPointer_static_extension) typedef T__struct_148PointerPointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t__struct_148pointerpointer.T__struct_148PointerPointer>;
