package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t_stringinterfaceptrpointer_static_extension.T_stringInterfacePtrPointer_static_extension) typedef T_stringInterfacePtrPointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t_stringinterfaceptrpointer.T_stringInterfacePtrPointer>;
