package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t_atomicheadtailindexpointer_static_extension.T_atomicHeadTailIndexPointer_static_extension) typedef T_atomicHeadTailIndexPointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t_atomicheadtailindexpointer.T_atomicHeadTailIndexPointer>;
