package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t_uint32interfaceptrpointer_static_extension.T_uint32InterfacePtrPointer_static_extension) typedef T_uint32InterfacePtrPointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t_uint32interfaceptrpointer.T_uint32InterfacePtrPointer>;
