package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t_goroutineprofilestatepointer_static_extension.T_goroutineProfileStatePointer_static_extension) typedef T_goroutineProfileStatePointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t_goroutineprofilestatepointer.T_goroutineProfileStatePointer>;
