package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t__struct_168pointerpointer_static_extension.T__struct_168PointerPointer_static_extension) typedef T__struct_168PointerPointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t__struct_168pointerpointer.T__struct_168PointerPointer>;
