package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t_reflectmethodvaluepointer_static_extension.T_reflectMethodValuePointer_static_extension) typedef T_reflectMethodValuePointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t_reflectmethodvaluepointer.T_reflectMethodValuePointer>;
