package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t_atomicspansetspinepointerpointer_static_extension.T_atomicSpanSetSpinePointerPointer_static_extension) typedef T_atomicSpanSetSpinePointerPointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t_atomicspansetspinepointerpointer.T_atomicSpanSetSpinePointerPointer>;
