package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_t__struct_150pointerpointer_static_extension.T__struct_150PointerPointer_static_extension) typedef T__struct_150PointerPointerPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_t__struct_150pointerpointer.T__struct_150PointerPointer>;
