package _internal.contextdottest;
import _internal.context_test.Context_test;
import stdgo._internal.testing.internal.testdeps.Testdeps;
import stdgo._internal.testing.Testing;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>(37, 37, ...[
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextAfterFuncCancel" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextafterfunccancel.testCustomContextAfterFuncCancel) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextAfterFuncTimeout" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextafterfunctimeout.testCustomContextAfterFuncTimeout) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextAfterFuncAfterFunc" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextafterfuncafterfunc.testCustomContextAfterFuncAfterFunc) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextAfterFuncUnregisterCancel" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextafterfuncunregistercancel.testCustomContextAfterFuncUnregisterCancel) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextAfterFuncUnregisterTimeout" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextafterfuncunregistertimeout.testCustomContextAfterFuncUnregisterTimeout) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextAfterFuncUnregisterAfterFunc" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextafterfuncunregisterafterfunc.testCustomContextAfterFuncUnregisterAfterFunc) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDeadlineExceededIsNetError" : stdgo.GoString), _internal.context_test.Context_test_testdeadlineexceededisneterror.testDeadlineExceededIsNetError) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestParentFinishesChild" : stdgo.GoString), _internal.context_test.Context_test_testparentfinisheschild.testParentFinishesChild) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestChildFinishesFirst" : stdgo.GoString), _internal.context_test.Context_test_testchildfinishesfirst.testChildFinishesFirst) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCancelRemoves" : stdgo.GoString), _internal.context_test.Context_test_testcancelremoves.testCancelRemoves) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextGoroutines" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextgoroutines.testCustomContextGoroutines) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestBackground" : stdgo.GoString), _internal.context_test.Context_test_testbackground.testBackground) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestTODO" : stdgo.GoString), _internal.context_test.Context_test_testtodo.testTODO) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestWithCancel" : stdgo.GoString), _internal.context_test.Context_test_testwithcancel.testWithCancel) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDeadline" : stdgo.GoString), _internal.context_test.Context_test_testdeadline.testDeadline) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestTimeout" : stdgo.GoString), _internal.context_test.Context_test_testtimeout.testTimeout) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCanceledTimeout" : stdgo.GoString), _internal.context_test.Context_test_testcanceledtimeout.testCanceledTimeout) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestValues" : stdgo.GoString), _internal.context_test.Context_test_testvalues.testValues) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAllocs" : stdgo.GoString), _internal.context_test.Context_test_testallocs.testAllocs) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestSimultaneousCancels" : stdgo.GoString), _internal.context_test.Context_test_testsimultaneouscancels.testSimultaneousCancels) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestInterlockedCancels" : stdgo.GoString), _internal.context_test.Context_test_testinterlockedcancels.testInterlockedCancels) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestLayersCancel" : stdgo.GoString), _internal.context_test.Context_test_testlayerscancel.testLayersCancel) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestLayersTimeout" : stdgo.GoString), _internal.context_test.Context_test_testlayerstimeout.testLayersTimeout) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestWithCancelCanceledParent" : stdgo.GoString), _internal.context_test.Context_test_testwithcancelcanceledparent.testWithCancelCanceledParent) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestWithCancelSimultaneouslyCanceledParent" : stdgo.GoString), _internal.context_test.Context_test_testwithcancelsimultaneouslycanceledparent.testWithCancelSimultaneouslyCanceledParent) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestWithValueChecksKey" : stdgo.GoString), _internal.context_test.Context_test_testwithvaluecheckskey.testWithValueChecksKey) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestInvalidDerivedFail" : stdgo.GoString), _internal.context_test.Context_test_testinvalidderivedfail.testInvalidDerivedFail) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDeadlineExceededSupportsTimeout" : stdgo.GoString), _internal.context_test.Context_test_testdeadlineexceededsupportstimeout.testDeadlineExceededSupportsTimeout) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCause" : stdgo.GoString), _internal.context_test.Context_test_testcause.testCause) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCauseRace" : stdgo.GoString), _internal.context_test.Context_test_testcauserace.testCauseRace) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestWithoutCancel" : stdgo.GoString), _internal.context_test.Context_test_testwithoutcancel.testWithoutCancel) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCustomContextPropagation" : stdgo.GoString), _internal.context_test.Context_test_testcustomcontextpropagation.testCustomContextPropagation) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAfterFuncCalledAfterCancel" : stdgo.GoString), _internal.context_test.Context_test_testafterfunccalledaftercancel.testAfterFuncCalledAfterCancel) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAfterFuncCalledAfterTimeout" : stdgo.GoString), _internal.context_test.Context_test_testafterfunccalledaftertimeout.testAfterFuncCalledAfterTimeout) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAfterFuncCalledImmediately" : stdgo.GoString), _internal.context_test.Context_test_testafterfunccalledimmediately.testAfterFuncCalledImmediately) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAfterFuncNotCalledAfterStop" : stdgo.GoString), _internal.context_test.Context_test_testafterfuncnotcalledafterstop.testAfterFuncNotCalledAfterStop) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAfterFuncCalledAsynchronously" : stdgo.GoString), _internal.context_test.Context_test_testafterfunccalledasynchronously.testAfterFuncCalledAsynchronously) : stdgo._internal.testing.Testing_internaltest.InternalTest)].concat([for (i in 37 ... (37 > 37 ? 37 : 37 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internaltest.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>(7, 7, ...[(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkCommonParentCancel" : stdgo.GoString), _internal.context_test.Context_test_benchmarkcommonparentcancel.benchmarkCommonParentCancel) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark), (new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkWithTimeout" : stdgo.GoString), _internal.context_test.Context_test_benchmarkwithtimeout.benchmarkWithTimeout) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark), (new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkCancelTree" : stdgo.GoString), _internal.context_test.Context_test_benchmarkcanceltree.benchmarkCancelTree) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark), (new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkCheckCanceled" : stdgo.GoString), _internal.context_test.Context_test_benchmarkcheckcanceled.benchmarkCheckCanceled) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark), (new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkContextCancelDone" : stdgo.GoString), _internal.context_test.Context_test_benchmarkcontextcanceldone.benchmarkContextCancelDone) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark), (new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkDeepValueNewGoRoutine" : stdgo.GoString), _internal.context_test.Context_test_benchmarkdeepvaluenewgoroutine.benchmarkDeepValueNewGoRoutine) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark), (new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkDeepValueSameGoRoutine" : stdgo.GoString), _internal.context_test.Context_test_benchmarkdeepvaluesamegoroutine.benchmarkDeepValueSameGoRoutine) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)].concat([for (i in 7 ... (7 > 7 ? 7 : 7 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>(7, 7, ...[(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleWithCancel" : stdgo.GoString), _internal.context_test.Context_test_examplewithcancel.exampleWithCancel, ("1\n2\n3\n4\n5\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample), (new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleWithDeadline" : stdgo.GoString), _internal.context_test.Context_test_examplewithdeadline.exampleWithDeadline, ("context deadline exceeded\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample), (new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleWithTimeout" : stdgo.GoString), _internal.context_test.Context_test_examplewithtimeout.exampleWithTimeout, ("context deadline exceeded\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample), (new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleWithValue" : stdgo.GoString), _internal.context_test.Context_test_examplewithvalue.exampleWithValue, ("found value: Go\nkey not found: color\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample), (new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleAfterFunc_cond" : stdgo.GoString), _internal.context_test.Context_test_exampleafterfunc_cond.exampleAfterFunc_cond, ("context deadline exceeded\ncontext deadline exceeded\ncontext deadline exceeded\ncontext deadline exceeded\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample), (new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleAfterFunc_connection" : stdgo.GoString), _internal.context_test.Context_test_exampleafterfunc_connection.exampleAfterFunc_connection, ("context deadline exceeded\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample), (new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleAfterFunc_merge" : stdgo.GoString), _internal.context_test.Context_test_exampleafterfunc_merge.exampleAfterFunc_merge, ("ctx2 canceled\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample)].concat([for (i in 7 ... (7 > 7 ? 7 : 7 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalexample.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>);
function main():Void {
    var _m = stdgo._internal.testing.Testing_mainstart.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps), _internal.gotype.Gotype___type__stdgodot_internaldottestingdotinternaldottestdepsdottestdeps_testdepsdottestdeps.__type__stdgodot_internaldottestingdotinternaldottestdepsdotTestdeps_testdepsdotTestDeps), _tests, _benchmarks, _fuzzTargets, _examples);
    //"file:///Users/o/Library/Caches/go-build/69/691c1ac698968849dbf3b16cb0dcc1b9f152751f97f5eb90a657efa112bd3a31-d#L149"
    #if (sys || hxnodejs) Sys.exit(_m.run()) #else null #end;
}
@:keep var __init_go2hx__ = {
    try {
        var __tmp__0 = _internal.contextdottest.Contextdottest._tests, __tmp__1 = _internal.contextdottest.Contextdottest._benchmarks, __tmp__2 = _internal.contextdottest.Contextdottest._fuzzTargets, __tmp__3 = _internal.contextdottest.Contextdottest._examples;
        stdgo._internal.testing.internal.testdeps.Testdeps_importpath.importPath = ("context" : stdgo.GoString);
    } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
    true;
};
