package stdgo._internal.testing.fstest;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.fs.Fs;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.sort.Sort;
import stdgo._internal.errors.Errors;
import stdgo._internal.io.Io;
import stdgo._internal.path.Path;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.testing.iotest.Iotest;
@:keep @:follow @:using(stdgo._internal.testing.fstest.Fstest_t_mapdir_static_extension.T_mapDir_static_extension) @:using(stdgo._internal.testing.fstest.Fstest_t_mapdirpointer_static_extension.T_mapDirPointer_static_extension) typedef T_mapDirPointer = stdgo.Pointer<stdgo._internal.testing.fstest.Fstest_t_mapdir.T_mapDir>;
