package stdgo._internal.testing.fstest;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.fs.Fs;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.sort.Sort;
import stdgo._internal.errors.Errors;
import stdgo._internal.io.Io;
import stdgo._internal.path.Path;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.testing.iotest.Iotest;
@:keep @:follow @:using(stdgo._internal.testing.fstest.Fstest_mapfs_static_extension.MapFS_static_extension) @:using(stdgo._internal.testing.fstest.Fstest_mapfspointer_static_extension.MapFSPointer_static_extension) typedef MapFSPointer = stdgo.Pointer<stdgo._internal.testing.fstest.Fstest_mapfs.MapFS>;
