package stdgo._internal.testing.fstest;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.fs.Fs;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.sort.Sort;
import stdgo._internal.errors.Errors;
import stdgo._internal.io.Io;
import stdgo._internal.path.Path;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.testing.iotest.Iotest;
@:keep @:follow @:using(stdgo._internal.testing.fstest.Fstest_t_openmapfilepointer_static_extension.T_openMapFilePointer_static_extension) typedef T_openMapFilePointerPointer = stdgo.Pointer<stdgo._internal.testing.fstest.Fstest_t_openmapfilepointer.T_openMapFilePointer>;
