package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_51pointerpointer_static_extension.T__struct_51PointerPointer_static_extension) typedef T__struct_51PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_51pointerpointer.T__struct_51PointerPointer>;
