package _internal.fmt_test;
@:named @:using(_internal.fmt_test.Fmt_test_t_renamedcomplex128_static_extension.T_renamedComplex128_static_extension) @:using(_internal.fmt_test.Fmt_test_t_renamedcomplex128_static_extension.T_renamedComplex128_static_extension) typedef T_renamedComplex128 = stdgo.GoComplex128;
