package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_42pointerpointer_static_extension.T__struct_42PointerPointer_static_extension) typedef T__struct_42PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_42pointerpointer.T__struct_42PointerPointer>;
