package _internal.fmt_test;
function testFormatString(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        var _tests = (new stdgo.Slice<_internal.fmt_test.Fmt_test_t__struct_55.T__struct_55>(10, 10, ...[({ _width : (-1000 : stdgo.GoInt), _prec : (-1000 : stdgo.GoInt), _flags : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), _result : ("%x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (-1000 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), _result : ("%.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (3 : stdgo.GoInt), _prec : (-1000 : stdgo.GoInt), _flags : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), _result : ("%3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), _result : ("%7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (-1000 : stdgo.GoInt), _prec : (-1000 : stdgo.GoInt), _flags : (" +-#0" : stdgo.GoString), _result : ("% +-#0x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : ("+" : stdgo.GoString), _result : ("%+7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (7 : stdgo.GoInt), _prec : (-3 : stdgo.GoInt), _flags : ("-" : stdgo.GoString), _result : ("%-7.-3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : (" " : stdgo.GoString), _result : ("% 7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : ("#" : stdgo.GoString), _result : ("%#7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : ("0" : stdgo.GoString), _result : ("%07.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55)].concat([for (i in 10 ... (10 > 10 ? 10 : 10 : stdgo.GoInt).toBasic()) ({ _width : (0 : stdgo.GoInt), _prec : (0 : stdgo.GoInt), _flags : ("" : stdgo.GoString), _result : ("" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_55.T__struct_55)])) : stdgo.Slice<_internal.fmt_test.Fmt_test_t__struct_55.T__struct_55>);
        //"file:///Users/o/.go/go1.21.3/src/fmt/state_test.go#L74"
        if (_tests != null) for (__2 => _test in _tests) {
            var _got = @:assignType (stdgo._internal.fmt.Fmt_formatstring.formatString(stdgo.Go.asInterface(_internal.fmt_test.Fmt_test__mkstate._mkState(_test._width, _test._prec, _test._flags?.__copy__()), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_t_teststatedott_teststate.__type___internaldotfmt_testdotFmt_test_t_teststatedotT_testState), (120 : stdgo.GoInt32))?.__copy__() : stdgo.GoString);
            //"file:///Users/o/.go/go1.21.3/src/fmt/state_test.go#L76"
            if (_got != (_test._result)) {
                //"file:///Users/o/.go/go1.21.3/src/fmt/state_test.go#L77"
                _t.errorf(("%v: got %s" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(_test, stdgo._internal.internal.reflect.GoType.structType([{ name : "_width", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_prec", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_flags", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, optional : false }, { name : "_result", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, optional : false }])), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.structType([{ name : "_width", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_prec", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(int_kind) }, optional : false }, { name : "_flags", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, optional : false }, { name : "_result", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.GoType.basic(string_kind) }, optional : false }]))), new stdgo.AnyInterface(_got, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
            };
        };
    }
