package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_37pointerpointer_static_extension.T__struct_37PointerPointer_static_extension) typedef T__struct_37PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_37pointerpointer.T__struct_37PointerPointer>;
