package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_47pointerpointer_static_extension.T__struct_47PointerPointer_static_extension) typedef T__struct_47PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_47pointerpointer.T__struct_47PointerPointer>;
