package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_39pointerpointer_static_extension.T__struct_39PointerPointer_static_extension) typedef T__struct_39PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_39pointerpointer.T__struct_39PointerPointer>;
