package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_22pointerpointer_static_extension.T__struct_22PointerPointer_static_extension) typedef T__struct_22PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_22pointerpointer.T__struct_22PointerPointer>;
