package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t_writestringformatterpointer_static_extension.T_writeStringFormatterPointer_static_extension) typedef T_writeStringFormatterPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t_writestringformatterpointer.T_writeStringFormatterPointer>;
