package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_53pointerpointer_static_extension.T__struct_53PointerPointer_static_extension) typedef T__struct_53PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_53pointerpointer.T__struct_53PointerPointer>;
