package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t_renameduintptr_static_extension.T_renamedUintptr_static_extension) @:using(_internal.fmt_test.Fmt_test_t_renameduintptrpointer_static_extension.T_renamedUintptrPointer_static_extension) typedef T_renamedUintptrPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t_renameduintptr.T_renamedUintptr>;
