package _internal.fmt_test;
var _overflowTests : stdgo.Slice<_internal.fmt_test.Fmt_test_scantest.ScanTest> = (new stdgo.Slice<_internal.fmt_test.Fmt_test_scantest.ScanTest>(11, 11, ...[
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("128" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__int8val._int8Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int8_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("32768" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__int16val._int16Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int16_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("-129" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__int8val._int8Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int8_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("-32769" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__int16val._int16Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(int16_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("256" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__uint8val._uint8Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint8_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("65536" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__uint16val._uint16Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(uint16_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("1e100" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__float32val._float32Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(float32_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("1e500" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__float64val._float64Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(float64_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("(1e100+0i)" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__complex64val._complex64Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(complex64_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("(1+1e100i)" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__complex64val._complex64Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(complex64_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest),
(new _internal.fmt_test.Fmt_test_scantest.ScanTest(("(1-1e500i)" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.pointer(_internal.fmt_test.Fmt_test__complex128val._complex128Val), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.pointerType({ get : () -> stdgo._internal.internal.reflect.GoType.basic(complex128_kind) }))), new stdgo.AnyInterface((0 : stdgo.GoInt), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(int_kind)))) : _internal.fmt_test.Fmt_test_scantest.ScanTest)].concat([for (i in 11 ... (11 > 11 ? 11 : 11 : stdgo.GoInt).toBasic()) ({} : _internal.fmt_test.Fmt_test_scantest.ScanTest)])) : stdgo.Slice<_internal.fmt_test.Fmt_test_scantest.ScanTest>);
