package _internal.fmt_test;
@:keep @:allow(_internal.fmt_test.Fmt_test.T_testNilDoesNotBecomeTyped___localname___B_55389Pointer_asInterface) class T_testNilDoesNotBecomeTyped___localname___B_55389Pointer_static_extension {

}
