package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_54pointerpointer_static_extension.T__struct_54PointerPointer_static_extension) typedef T__struct_54PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_54pointerpointer.T__struct_54PointerPointer>;
