package _internal.fmt_test;
function testStructPrinter(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        {};
        var _s:_internal.fmt_test.Fmt_test_t_teststructprinter___localname___t_47832.T_testStructPrinter___localname___T_47832 = ({} : _internal.fmt_test.Fmt_test_t_teststructprinter___localname___t_47832.T_testStructPrinter___localname___T_47832);
        _s._a = ("abc" : stdgo.GoString);
        _s._b = ("def" : stdgo.GoString);
        _s._c = (123 : stdgo.GoInt);
        var _tests = (new stdgo.Slice<_internal.fmt_test.Fmt_test_t__struct_37.T__struct_37>(3, 3, ...[({ _fmt : ("%v" : stdgo.GoString), _out : ("{abc def 123}" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_37.T__struct_37), ({ _fmt : ("%+v" : stdgo.GoString), _out : ("{a:abc b:def c:123}" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_37.T__struct_37), ({ _fmt : ("%#v" : stdgo.GoString), _out : ("fmt_test.T{a:\"abc\", b:\"def\", c:123}" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_37.T__struct_37)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({ _fmt : ("" : stdgo.GoString), _out : ("" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_t__struct_37.T__struct_37)])) : stdgo.Slice<_internal.fmt_test.Fmt_test_t__struct_37.T__struct_37>);
        //"file:///Users/o/.go/go1.21.3/src/fmt/fmt_test.go#L1534"
        if (_tests != null) for (__2 => _tt in _tests) {
            var _out = @:assignType (stdgo._internal.fmt.Fmt_sprintf.sprintf(_tt._fmt?.__copy__(), new stdgo.AnyInterface(stdgo.Go.asInterface(_s, _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_t_teststructprinter___localname___t_47832dott_teststructprinter___localname___t_47832.__type___internaldotfmt_testdotFmt_test_t_teststructprinter___localname___t_47832dotT_testStructPrinter___localname___T_47832), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_t_teststructprinter___localname___t_47832dott_teststructprinter___localname___t_47832.__type___internaldotfmt_testdotFmt_test_t_teststructprinter___localname___t_47832dotT_testStructPrinter___localname___T_47832)))?.__copy__() : stdgo.GoString);
            //"file:///Users/o/.go/go1.21.3/src/fmt/fmt_test.go#L1536"
            if (_out != (_tt._out)) {
                //"file:///Users/o/.go/go1.21.3/src/fmt/fmt_test.go#L1537"
                _t.errorf(("Sprintf(%q, s) = %#q, want %#q" : stdgo.GoString), new stdgo.AnyInterface(_tt._fmt, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(_out, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(_tt._out, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
            };
            _out = stdgo._internal.fmt.Fmt_sprintf.sprintf(_tt._fmt?.__copy__(), new stdgo.AnyInterface(stdgo.Go.asInterface((stdgo.Go.setRef(_s, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_t_teststructprinter___localname___t_47832dott_teststructprinter___localname___t_47832.__type___internaldotfmt_testdotFmt_test_t_teststructprinter___localname___t_47832dotT_testStructPrinter___localname___T_47832 })) : stdgo.Ref<_internal.fmt_test.Fmt_test_t_teststructprinter___localname___t_47832.T_testStructPrinter___localname___T_47832>), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_t_teststructprinter___localname___t_47832dott_teststructprinter___localname___t_47832.__type___internaldotfmt_testdotFmt_test_t_teststructprinter___localname___t_47832dotT_testStructPrinter___localname___T_47832), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_t_teststructprinter___localname___t_47832dott_teststructprinter___localname___t_47832.__type___internaldotfmt_testdotFmt_test_t_teststructprinter___localname___t_47832dotT_testStructPrinter___localname___T_47832 }))))?.__copy__();
            //"file:///Users/o/.go/go1.21.3/src/fmt/fmt_test.go#L1541"
            if (_out != ((("&" : stdgo.GoString) + _tt._out?.__copy__() : stdgo.GoString))) {
                //"file:///Users/o/.go/go1.21.3/src/fmt/fmt_test.go#L1542"
                _t.errorf(("Sprintf(%q, &s) = %#q, want %#q" : stdgo.GoString), new stdgo.AnyInterface(_tt._fmt, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface(_out, new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))), new stdgo.AnyInterface((("&" : stdgo.GoString) + _tt._out?.__copy__() : stdgo.GoString), new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.GoType.basic(string_kind))));
            };
        };
    }
