package _internal.fmt_test;
function testStringer(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        var _s = @:assignType (stdgo._internal.fmt.Fmt_sprintf.sprintf(("%v %v %v %v %v" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((0 : _internal.fmt_test.Fmt_test_ti.TI), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tidotti.__type___internaldotfmt_testdotFmt_test_tidotTI), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tidotti.__type___internaldotfmt_testdotFmt_test_tidotTI)), new stdgo.AnyInterface(stdgo.Go.asInterface((1 : _internal.fmt_test.Fmt_test_ti8.TI8), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti8dotti8.__type___internaldotfmt_testdotFmt_test_ti8dotTI8), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti8dotti8.__type___internaldotfmt_testdotFmt_test_ti8dotTI8)), new stdgo.AnyInterface(stdgo.Go.asInterface((2 : _internal.fmt_test.Fmt_test_ti16.TI16), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti16dotti16.__type___internaldotfmt_testdotFmt_test_ti16dotTI16), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti16dotti16.__type___internaldotfmt_testdotFmt_test_ti16dotTI16)), new stdgo.AnyInterface(stdgo.Go.asInterface((3 : _internal.fmt_test.Fmt_test_ti32.TI32), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti32dotti32.__type___internaldotfmt_testdotFmt_test_ti32dotTI32), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti32dotti32.__type___internaldotfmt_testdotFmt_test_ti32dotTI32)), new stdgo.AnyInterface(stdgo.Go.asInterface((4i64 : _internal.fmt_test.Fmt_test_ti64.TI64), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti64dotti64.__type___internaldotfmt_testdotFmt_test_ti64dotTI64), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_ti64dotti64.__type___internaldotfmt_testdotFmt_test_ti64dotTI64)))?.__copy__() : stdgo.GoString);
        //"file:///Users/o/.go/go1.21.3/src/fmt/stringer_test.go#L54"
        _internal.fmt_test.Fmt_test__check._check(_t, _s?.__copy__(), ("I: 0 I8: 1 I16: 2 I32: 3 I64: 4" : stdgo.GoString));
        _s = stdgo._internal.fmt.Fmt_sprintf.sprintf(("%v %v %v %v %v %v" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((5u32 : _internal.fmt_test.Fmt_test_tu.TU), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tudottu.__type___internaldotfmt_testdotFmt_test_tudotTU), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tudottu.__type___internaldotfmt_testdotFmt_test_tudotTU)), new stdgo.AnyInterface(stdgo.Go.asInterface((6 : _internal.fmt_test.Fmt_test_tu8.TU8), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu8dottu8.__type___internaldotfmt_testdotFmt_test_tu8dotTU8), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu8dottu8.__type___internaldotfmt_testdotFmt_test_tu8dotTU8)), new stdgo.AnyInterface(stdgo.Go.asInterface((7 : _internal.fmt_test.Fmt_test_tu16.TU16), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu16dottu16.__type___internaldotfmt_testdotFmt_test_tu16dotTU16), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu16dottu16.__type___internaldotfmt_testdotFmt_test_tu16dotTU16)), new stdgo.AnyInterface(stdgo.Go.asInterface((8u32 : _internal.fmt_test.Fmt_test_tu32.TU32), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu32dottu32.__type___internaldotfmt_testdotFmt_test_tu32dotTU32), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu32dottu32.__type___internaldotfmt_testdotFmt_test_tu32dotTU32)), new stdgo.AnyInterface(stdgo.Go.asInterface((9i64 : _internal.fmt_test.Fmt_test_tu64.TU64), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu64dottu64.__type___internaldotfmt_testdotFmt_test_tu64dotTU64), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tu64dottu64.__type___internaldotfmt_testdotFmt_test_tu64dotTU64)), new stdgo.AnyInterface(stdgo.Go.asInterface((new stdgo.GoUIntptr((new stdgo.GoUIntptr(10) : _internal.fmt_test.Fmt_test_tui.TUI)) : _internal.fmt_test.Fmt_test_tui.TUI), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tuidottui.__type___internaldotfmt_testdotFmt_test_tuidotTUI), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tuidottui.__type___internaldotfmt_testdotFmt_test_tuidotTUI)))?.__copy__();
        //"file:///Users/o/.go/go1.21.3/src/fmt/stringer_test.go#L56"
        _internal.fmt_test.Fmt_test__check._check(_t, _s?.__copy__(), ("U: 5 U8: 6 U16: 7 U32: 8 U64: 9 UI: 10" : stdgo.GoString));
        _s = stdgo._internal.fmt.Fmt_sprintf.sprintf(("%v %v %v" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface(((1 : stdgo.GoFloat64) : _internal.fmt_test.Fmt_test_tf.TF), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tfdottf.__type___internaldotfmt_testdotFmt_test_tfdotTF), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tfdottf.__type___internaldotfmt_testdotFmt_test_tfdotTF)), new stdgo.AnyInterface(stdgo.Go.asInterface(((2 : stdgo.GoFloat64) : _internal.fmt_test.Fmt_test_tf32.TF32), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tf32dottf32.__type___internaldotfmt_testdotFmt_test_tf32dotTF32), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tf32dottf32.__type___internaldotfmt_testdotFmt_test_tf32dotTF32)), new stdgo.AnyInterface(stdgo.Go.asInterface(((3 : stdgo.GoFloat64) : _internal.fmt_test.Fmt_test_tf64.TF64), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tf64dottf64.__type___internaldotfmt_testdotFmt_test_tf64dotTF64), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tf64dottf64.__type___internaldotfmt_testdotFmt_test_tf64dotTF64)))?.__copy__();
        //"file:///Users/o/.go/go1.21.3/src/fmt/stringer_test.go#L58"
        _internal.fmt_test.Fmt_test__check._check(_t, _s?.__copy__(), ("F: 1.000000 F32: 2.000000 F64: 3.000000" : stdgo.GoString));
        _s = stdgo._internal.fmt.Fmt_sprintf.sprintf(("%v %v" : stdgo.GoString), new stdgo.AnyInterface(stdgo.Go.asInterface((true : _internal.fmt_test.Fmt_test_tb.TB), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tbdottb.__type___internaldotfmt_testdotFmt_test_tbdotTB), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tbdottb.__type___internaldotfmt_testdotFmt_test_tbdotTB)), new stdgo.AnyInterface(stdgo.Go.asInterface((("x" : stdgo.GoString) : _internal.fmt_test.Fmt_test_ts.TS), _internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tsdotts.__type___internaldotfmt_testdotFmt_test_tsdotTS), new stdgo._internal.internal.reflect.Reflect._Type(_internal.gotype.Gotype___type___internaldotfmt_testdotfmt_test_tsdotts.__type___internaldotfmt_testdotFmt_test_tsdotTS)))?.__copy__();
        //"file:///Users/o/.go/go1.21.3/src/fmt/stringer_test.go#L60"
        _internal.fmt_test.Fmt_test__check._check(_t, _s?.__copy__(), ("B: true S: \"x\"" : stdgo.GoString));
    }
