package _internal.fmt_test;
@:keep @:follow @:using(_internal.fmt_test.Fmt_test_t__struct_48pointerpointer_static_extension.T__struct_48PointerPointer_static_extension) typedef T__struct_48PointerPointerPointer = stdgo.Pointer<_internal.fmt_test.Fmt_test_t__struct_48pointerpointer.T__struct_48PointerPointer>;
