package _internal.fmtdottest;
import _internal.fmt_test.Fmt_test;
import stdgo._internal.testing.internal.testdeps.Testdeps;
import stdgo._internal.testing.Testing;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>(51, 51, ...[
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestErrorf" : stdgo.GoString), _internal.fmt_test.Fmt_test_testerrorf.testErrorf) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestFmtInterface" : stdgo.GoString), _internal.fmt_test.Fmt_test_testfmtinterface.testFmtInterface) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestSprintf" : stdgo.GoString), _internal.fmt_test.Fmt_test_testsprintf.testSprintf) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestComplexFormatting" : stdgo.GoString), _internal.fmt_test.Fmt_test_testcomplexformatting.testComplexFormatting) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReorder" : stdgo.GoString), _internal.fmt_test.Fmt_test_testreorder.testReorder) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCountMallocs" : stdgo.GoString), _internal.fmt_test.Fmt_test_testcountmallocs.testCountMallocs) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestFlagParser" : stdgo.GoString), _internal.fmt_test.Fmt_test_testflagparser.testFlagParser) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestStructPrinter" : stdgo.GoString), _internal.fmt_test.Fmt_test_teststructprinter.testStructPrinter) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestSlicePrinter" : stdgo.GoString), _internal.fmt_test.Fmt_test_testsliceprinter.testSlicePrinter) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestMapPrinter" : stdgo.GoString), _internal.fmt_test.Fmt_test_testmapprinter.testMapPrinter) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestEmptyMap" : stdgo.GoString), _internal.fmt_test.Fmt_test_testemptymap.testEmptyMap) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestBlank" : stdgo.GoString), _internal.fmt_test.Fmt_test_testblank.testBlank) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestBlankln" : stdgo.GoString), _internal.fmt_test.Fmt_test_testblankln.testBlankln) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestFormatterPrintln" : stdgo.GoString), _internal.fmt_test.Fmt_test_testformatterprintln.testFormatterPrintln) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestWidthAndPrecision" : stdgo.GoString), _internal.fmt_test.Fmt_test_testwidthandprecision.testWidthAndPrecision) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestPanics" : stdgo.GoString), _internal.fmt_test.Fmt_test_testpanics.testPanics) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestBadVerbRecursion" : stdgo.GoString), _internal.fmt_test.Fmt_test_testbadverbrecursion.testBadVerbRecursion) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestIsSpace" : stdgo.GoString), _internal.fmt_test.Fmt_test_testisspace.testIsSpace) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestNilDoesNotBecomeTyped" : stdgo.GoString), _internal.fmt_test.Fmt_test_testnildoesnotbecometyped.testNilDoesNotBecomeTyped) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestFormatterFlags" : stdgo.GoString), _internal.fmt_test.Fmt_test_testformatterflags.testFormatterFlags) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestParsenum" : stdgo.GoString), _internal.fmt_test.Fmt_test_testparsenum.testParsenum) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAppendf" : stdgo.GoString), _internal.fmt_test.Fmt_test_testappendf.testAppendf) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAppend" : stdgo.GoString), _internal.fmt_test.Fmt_test_testappend.testAppend) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAppendln" : stdgo.GoString), _internal.fmt_test.Fmt_test_testappendln.testAppendln) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScan" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscan.testScan) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanln" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanln.testScanln) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanf" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanf.testScanf) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanOverflow" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanoverflow.testScanOverflow) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestNaN" : stdgo.GoString), _internal.fmt_test.Fmt_test_testnan.testNaN) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestInf" : stdgo.GoString), _internal.fmt_test.Fmt_test_testinf.testInf) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanfMulti" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanfmulti.testScanfMulti) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanMultiple" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanmultiple.testScanMultiple) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanEmpty" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanempty.testScanEmpty) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanNotPointer" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscannotpointer.testScanNotPointer) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanlnNoNewline" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanlnnonewline.testScanlnNoNewline) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanlnWithMiddleNewline" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanlnwithmiddlenewline.testScanlnWithMiddleNewline) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestEOF" : stdgo.GoString), _internal.fmt_test.Fmt_test_testeof.testEOF) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestEOFAtEndOfInput" : stdgo.GoString), _internal.fmt_test.Fmt_test_testeofatendofinput.testEOFAtEndOfInput) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestEOFAllTypes" : stdgo.GoString), _internal.fmt_test.Fmt_test_testeofalltypes.testEOFAllTypes) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestUnreadRuneWithBufio" : stdgo.GoString), _internal.fmt_test.Fmt_test_testunreadrunewithbufio.testUnreadRuneWithBufio) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestMultiLine" : stdgo.GoString), _internal.fmt_test.Fmt_test_testmultiline.testMultiLine) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestLineByLineFscanf" : stdgo.GoString), _internal.fmt_test.Fmt_test_testlinebylinefscanf.testLineByLineFscanf) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanStateCount" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanstatecount.testScanStateCount) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanInts" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanints.testScanInts) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestHexBytes" : stdgo.GoString), _internal.fmt_test.Fmt_test_testhexbytes.testHexBytes) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanNewlinesAreSpaces" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscannewlinesarespaces.testScanNewlinesAreSpaces) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanlnNewlinesTerminate" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanlnnewlinesterminate.testScanlnNewlinesTerminate) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestScanfNewlineMatchFormat" : stdgo.GoString), _internal.fmt_test.Fmt_test_testscanfnewlinematchformat.testScanfNewlineMatchFormat) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestHexByte" : stdgo.GoString), _internal.fmt_test.Fmt_test_testhexbyte.testHexByte) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestFormatString" : stdgo.GoString), _internal.fmt_test.Fmt_test_testformatstring.testFormatString) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestStringer" : stdgo.GoString), _internal.fmt_test.Fmt_test_teststringer.testStringer) : stdgo._internal.testing.Testing_internaltest.InternalTest)].concat([for (i in 51 ... (51 > 51 ? 51 : 51 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internaltest.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>(25, 25, ...[
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfPadding" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfpadding.benchmarkSprintfPadding) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfEmpty" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfempty.benchmarkSprintfEmpty) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfString" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfstring.benchmarkSprintfString) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfTruncateString" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintftruncatestring.benchmarkSprintfTruncateString) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfTruncateBytes" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintftruncatebytes.benchmarkSprintfTruncateBytes) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfSlowParsingPath" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfslowparsingpath.benchmarkSprintfSlowParsingPath) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfQuoteString" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfquotestring.benchmarkSprintfQuoteString) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfInt" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfint.benchmarkSprintfInt) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfIntInt" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfintint.benchmarkSprintfIntInt) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfPrefixedInt" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfprefixedint.benchmarkSprintfPrefixedInt) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfFloat" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintffloat.benchmarkSprintfFloat) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfComplex" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfcomplex.benchmarkSprintfComplex) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfBoolean" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfboolean.benchmarkSprintfBoolean) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfHexString" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfhexstring.benchmarkSprintfHexString) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfHexBytes" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfhexbytes.benchmarkSprintfHexBytes) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfBytes" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfbytes.benchmarkSprintfBytes) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfStringer" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfstringer.benchmarkSprintfStringer) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkSprintfStructure" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarksprintfstructure.benchmarkSprintfStructure) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkManyArgs" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarkmanyargs.benchmarkManyArgs) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkFprintInt" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarkfprintint.benchmarkFprintInt) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkFprintfBytes" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarkfprintfbytes.benchmarkFprintfBytes) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkFprintIntNoAlloc" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarkfprintintnoalloc.benchmarkFprintIntNoAlloc) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkScanInts" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarkscanints.benchmarkScanInts) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkScanRecursiveInt" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarkscanrecursiveint.benchmarkScanRecursiveInt) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkScanRecursiveIntReaderWrapper" : stdgo.GoString), _internal.fmt_test.Fmt_test_benchmarkscanrecursiveintreaderwrapper.benchmarkScanRecursiveIntReaderWrapper) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)].concat([for (i in 25 ... (25 > 25 ? 25 : 25 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>(17, 17, ...[
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleErrorf" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleerrorf.exampleErrorf, ("user \"bueller\" (id 17) not found\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleFscanf" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplefscanf.exampleFscanf, ("5 true gophers\n3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleFscanln" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplefscanln.exampleFscanln, ("3: dmr, 1771, 1.618034\n3: ken, 271828, 3.141590\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleSscanf" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplesscanf.exampleSscanf, ("2: Kim, 22\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExamplePrint" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleprint.examplePrint, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExamplePrintln" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleprintln.examplePrintln, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExamplePrintf" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleprintf.examplePrintf, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleSprint" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplesprint.exampleSprint, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleSprintln" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplesprintln.exampleSprintln, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleSprintf" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplesprintf.exampleSprintf, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleFprint" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplefprint.exampleFprint, ("Kim is 22 years old.\n21 bytes written.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleFprintln" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplefprintln.exampleFprintln, ("Kim is 22 years old.\n21 bytes written.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleFprintf" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplefprintf.exampleFprintf, ("Kim is 22 years old.\n21 bytes written.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("Example_printers" : stdgo.GoString), _internal.fmt_test.Fmt_test_example_printers.example_printers, ("The vector (3 4) has length 5.\nThe vector ( 3 4 ) has length 5 .\nThe vector (3 4) has length 5.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("Example_formats" : stdgo.GoString), _internal.fmt_test.Fmt_test_example_formats.example_formats, ("23\n23\n23\nint *int\ntrue true\n42 42 2a 52 101010\n3.141592653589793 3.141592653589793 3.14 (  3.14) 3.141593e+00\n(110.7+22.5i) (110.7+22.5i) (110.70+22.50i) (1.11e+02+2.25e+01i)\n128512 128512 😀 \'😀\' U+1F600 U+1F600 \'😀\'\nfoo \"bar\" foo \"bar\" \"foo \\\"bar\\\"\" `foo \"bar\"`\nmap[dachshund:false peanut:true] map[string]bool{\"dachshund\":false, \"peanut\":true}\n{Kim 22} {Name:Kim Age:22} struct { Name string; Age int }{Name:\"Kim\", Age:22}\n&{Kim 22} 0x0\n[Kitano Kobayashi Kurosawa Miyazaki Ozu] [\"Kitano\" \"Kobayashi\" \"Kurosawa\" \"Miyazaki\" \"Ozu\"]\n[Kitano Kobayashi Kurosawa] [\"Kitano\" \"Kobayashi\" \"Kurosawa\"] []string{\"Kitano\", \"Kobayashi\", \"Kurosawa\"}\n[97 226 140 152] [97 226 140 152] a⌘ \"a⌘\" 61e28c98 61 e2 8c 98\n1973-11-29 21:33:09 +0000 UTC \"1973-11-29 21:33:09 +0000 UTC\"\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleGoStringer" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplegostringer.exampleGoStringer, ("Person{Name: \"Warren\", Age: 31, Addr: &Address{City: \"Denver\", State: \"CO\", Country: \"U.S.A.\"}}\nPerson{Name: \"Theia\", Age: 4}\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleStringer" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplestringer.exampleStringer, ("Gopher (2)\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample)].concat([for (i in 17 ... (17 > 17 ? 17 : 17 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalexample.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>);
function main():Void {
    var _m = stdgo._internal.testing.Testing_mainstart.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps), _internal.gotype.Gotype___type__stdgodot_internaldottestingdotinternaldottestdepsdottestdeps_testdepsdottestdeps.__type__stdgodot_internaldottestingdotinternaldottestdepsdotTestdeps_testdepsdotTestDeps), _tests, _benchmarks, _fuzzTargets, _examples);
    //"file:///Users/o/Library/Caches/go-build/66/665da5d4c977fc2a206006294ded03ebd6df63735e00381c714cf30190ea5398-d#L233"
    #if (sys || hxnodejs) Sys.exit(_m.run()) #else null #end;
}
@:keep var __init_go2hx__ = {
    try {
        var __tmp__0 = _internal.fmtdottest.Fmtdottest._tests, __tmp__1 = _internal.fmtdottest.Fmtdottest._benchmarks, __tmp__2 = _internal.fmtdottest.Fmtdottest._fuzzTargets, __tmp__3 = _internal.fmtdottest.Fmtdottest._examples;
        stdgo._internal.testing.internal.testdeps.Testdeps_importpath.importPath = ("fmt" : stdgo.GoString);
    } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
    true;
};
