package _internal.io.fs_test;
var _isValidPathTests : stdgo.Slice<_internal.io.fs_test.Fs_test_t__struct_152.T__struct_152> = (new stdgo.Slice<_internal.io.fs_test.Fs_test_t__struct_152.T__struct_152>(23, 23, ...[
({ _name : ("." : stdgo.GoString), _ok : true } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x" : stdgo.GoString), _ok : true } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x/y" : stdgo.GoString), _ok : true } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : (stdgo.Go.str() : stdgo.GoString)?.__copy__(), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : (".." : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("/" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x/" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("/x" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x/y/" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("/x/y" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("./" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("./x" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x/." : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x/./y" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("../" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("../x" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x/.." : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x/../y" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x//y" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x\\" : stdgo.GoString), _ok : true } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x\\y" : stdgo.GoString), _ok : true } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("x:y" : stdgo.GoString), _ok : true } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152),
({ _name : ("\\x" : stdgo.GoString), _ok : true } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152)].concat([for (i in 23 ... (23 > 23 ? 23 : 23 : stdgo.GoInt).toBasic()) ({ _name : ("" : stdgo.GoString), _ok : false } : _internal.io.fs_test.Fs_test_t__struct_152.T__struct_152)])) : stdgo.Slice<_internal.io.fs_test.Fs_test_t__struct_152.T__struct_152>);
