package stdgo._internal.mime;
import stdgo._internal.errors.Errors;
import stdgo._internal.encoding.base64.Base64;
import stdgo._internal.strings.Strings;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.sort.Sort;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.os.Os;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.io.Io;
import stdgo._internal.unicode.utf8.Utf8;
@:keep @:follow @:using(stdgo._internal.mime.Mime_worddecoder_static_extension.WordDecoder_static_extension) @:using(stdgo._internal.mime.Mime_worddecoderpointer_static_extension.WordDecoderPointer_static_extension) typedef WordDecoderPointer = stdgo.Pointer<stdgo._internal.mime.Mime_worddecoder.WordDecoder>;
