package _internal.net.textprotodottest;
import stdgo._internal.net.textproto.Textproto;
import stdgo._internal.testing.internal.testdeps.Testdeps;
import stdgo._internal.testing.Testing;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>(25, 25, ...[
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCanonicalMIMEHeaderKey" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testcanonicalmimeheaderkey.testCanonicalMIMEHeaderKey) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestMIMEHeaderMultipleValues" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testmimeheadermultiplevalues.testMIMEHeaderMultipleValues) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadLine" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadline.testReadLine) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadContinuedLine" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadcontinuedline.testReadContinuedLine) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadCodeLine" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadcodeline.testReadCodeLine) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadDotLines" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreaddotlines.testReadDotLines) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadDotBytes" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreaddotbytes.testReadDotBytes) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeader" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheader.testReadMIMEHeader) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeaderSingle" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheadersingle.testReadMIMEHeaderSingle) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReaderUpcomingHeaderKeys" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreaderupcomingheaderkeys.testReaderUpcomingHeaderKeys) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeaderNoKey" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheadernokey.testReadMIMEHeaderNoKey) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestLargeReadMIMEHeader" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testlargereadmimeheader.testLargeReadMIMEHeader) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeaderNonCompliant" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheadernoncompliant.testReadMIMEHeaderNonCompliant) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeaderMalformed" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheadermalformed.testReadMIMEHeaderMalformed) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeaderBytes" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheaderbytes.testReadMIMEHeaderBytes) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeaderTrimContinued" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheadertrimcontinued.testReadMIMEHeaderTrimContinued) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMIMEHeaderAllocations" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmimeheaderallocations.testReadMIMEHeaderAllocations) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestRFC959Lines" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testrfc959lines.testRFC959Lines) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestReadMultiLineError" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testreadmultilineerror.testReadMultiLineError) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestCommonHeaders" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testcommonheaders.testCommonHeaders) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestIssue46363" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testissue46363.testIssue46363) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestPrintfLine" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testprintfline.testPrintfLine) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDotWriter" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testdotwriter.testDotWriter) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDotWriterCloseEmptyWrite" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testdotwritercloseemptywrite.testDotWriterCloseEmptyWrite) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDotWriterCloseNoWrite" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_testdotwriterclosenowrite.testDotWriterCloseNoWrite) : stdgo._internal.testing.Testing_internaltest.InternalTest)].concat([for (i in 25 ... (25 > 25 ? 25 : 25 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internaltest.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>(2, 2, ...[(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkReadMIMEHeader" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_benchmarkreadmimeheader.benchmarkReadMIMEHeader) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark), (new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkUncommon" : stdgo.GoString), stdgo._internal.net.textproto.Textproto_benchmarkuncommon.benchmarkUncommon) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalexample.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>);
function main():Void {
    var _m = stdgo._internal.testing.Testing_mainstart.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps), _internal.gotype.Gotype___type__stdgodot_internaldottestingdotinternaldottestdepsdottestdeps_testdepsdottestdeps.__type__stdgodot_internaldottestingdotinternaldottestdepsdotTestdeps_testdepsdotTestDeps), _tests, _benchmarks, _fuzzTargets, _examples);
    //"file:///Users/o/Library/Caches/go-build/cb/cbbe20961f878b350848259206cdb62edaebe4bcd80c7ccf0e9e0f9ab9d58a75-d#L99"
    #if (sys || hxnodejs) Sys.exit(_m.run()) #else null #end;
}
@:keep var __init_go2hx__ = {
    try {
        var __tmp__0 = _internal.net.textprotodottest.Textprotodottest._tests, __tmp__1 = _internal.net.textprotodottest.Textprotodottest._benchmarks, __tmp__2 = _internal.net.textprotodottest.Textprotodottest._fuzzTargets, __tmp__3 = _internal.net.textprotodottest.Textprotodottest._examples;
        stdgo._internal.testing.internal.testdeps.Testdeps_importpath.importPath = ("net/textproto" : stdgo.GoString);
    } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
    true;
};
