package _internal.unicode.utf8dottest;
import _internal.unicode.utf8_test.Utf8_test;
import stdgo._internal.testing.internal.testdeps.Testdeps;
import stdgo._internal.testing.Testing;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>(14, 14, ...[
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestConstants" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testconstants.testConstants) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestFullRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testfullrune.testFullRune) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestEncodeRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testencoderune.testEncodeRune) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestAppendRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testappendrune.testAppendRune) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDecodeRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testdecoderune.testDecodeRune) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDecodeSurrogateRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testdecodesurrogaterune.testDecodeSurrogateRune) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestSequencing" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testsequencing.testSequencing) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestRuntimeConversion" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testruntimeconversion.testRuntimeConversion) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestDecodeInvalidSequence" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testdecodeinvalidsequence.testDecodeInvalidSequence) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestNegativeRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testnegativerune.testNegativeRune) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestRuneCount" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testrunecount.testRuneCount) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestRuneLen" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testrunelen.testRuneLen) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestValid" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testvalid.testValid) : stdgo._internal.testing.Testing_internaltest.InternalTest),
(new stdgo._internal.testing.Testing_internaltest.InternalTest(("TestValidRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_testvalidrune.testValidRune) : stdgo._internal.testing.Testing_internaltest.InternalTest)].concat([for (i in 14 ... (14 > 14 ? 14 : 14 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internaltest.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing_internaltest.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>(21, 21, ...[
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkRuneCountTenASCIIChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkrunecounttenasciichars.benchmarkRuneCountTenASCIIChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkRuneCountTenJapaneseChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkrunecounttenjapanesechars.benchmarkRuneCountTenJapaneseChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkRuneCountInStringTenASCIIChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkrunecountinstringtenasciichars.benchmarkRuneCountInStringTenASCIIChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkRuneCountInStringTenJapaneseChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkrunecountinstringtenjapanesechars.benchmarkRuneCountInStringTenJapaneseChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidTenASCIIChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidtenasciichars.benchmarkValidTenASCIIChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValid100KASCIIChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalid100kasciichars.benchmarkValid100KASCIIChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidTenJapaneseChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidtenjapanesechars.benchmarkValidTenJapaneseChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidLongMostlyASCII" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidlongmostlyascii.benchmarkValidLongMostlyASCII) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidLongJapanese" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidlongjapanese.benchmarkValidLongJapanese) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidStringTenASCIIChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidstringtenasciichars.benchmarkValidStringTenASCIIChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidString100KASCIIChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidstring100kasciichars.benchmarkValidString100KASCIIChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidStringTenJapaneseChars" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidstringtenjapanesechars.benchmarkValidStringTenJapaneseChars) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidStringLongMostlyASCII" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidstringlongmostlyascii.benchmarkValidStringLongMostlyASCII) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkValidStringLongJapanese" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkvalidstringlongjapanese.benchmarkValidStringLongJapanese) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkEncodeASCIIRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkencodeasciirune.benchmarkEncodeASCIIRune) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkEncodeJapaneseRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkencodejapaneserune.benchmarkEncodeJapaneseRune) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkAppendASCIIRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkappendasciirune.benchmarkAppendASCIIRune) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkAppendJapaneseRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkappendjapaneserune.benchmarkAppendJapaneseRune) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkDecodeASCIIRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkdecodeasciirune.benchmarkDecodeASCIIRune) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkDecodeJapaneseRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkdecodejapaneserune.benchmarkDecodeJapaneseRune) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark),
(new stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark(("BenchmarkFullRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_benchmarkfullrune.benchmarkFullRune) : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)].concat([for (i in 21 ... (21 > 21 ? 21 : 21 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalbenchmark.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalfuzztarget.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>(16, 16, ...[
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleDecodeLastRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampledecodelastrune.exampleDecodeLastRune, ("界 3\n世 3\n  1\n, 1\no 1\nl 1\nl 1\ne 1\nH 1\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleDecodeLastRuneInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampledecodelastruneinstring.exampleDecodeLastRuneInString, ("界 3\n世 3\n  1\n, 1\no 1\nl 1\nl 1\ne 1\nH 1\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleDecodeRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampledecoderune.exampleDecodeRune, ("H 1\ne 1\nl 1\nl 1\no 1\n, 1\n  1\n世 3\n界 3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleDecodeRuneInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampledecoderuneinstring.exampleDecodeRuneInString, ("H 1\ne 1\nl 1\nl 1\no 1\n, 1\n  1\n世 3\n界 3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleEncodeRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleencoderune.exampleEncodeRune, ("[228 184 150]\n3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleEncodeRune_outOfRange" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleencoderune_outofrange.exampleEncodeRune_outOfRange, ("0: [239 191 189] � 3\n1: [239 191 189] � 3\n2: [239 191 189] � 3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleFullRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplefullrune.exampleFullRune, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleFullRuneInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplefullruneinstring.exampleFullRuneInString, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleRuneCount" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplerunecount.exampleRuneCount, ("bytes = 13\nrunes = 9\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleRuneCountInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplerunecountinstring.exampleRuneCountInString, ("bytes = 13\nrunes = 9\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleRuneLen" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplerunelen.exampleRuneLen, ("1\n3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleRuneStart" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplerunestart.exampleRuneStart, ("true\ntrue\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleValid" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplevalid.exampleValid, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleValidRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplevalidrune.exampleValidRune, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleValidString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_examplevalidstring.exampleValidString, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample),
(new stdgo._internal.testing.Testing_internalexample.InternalExample(("ExampleAppendRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleappendrune.exampleAppendRune, ("𐀀\ninit𐀀\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_internalexample.InternalExample)].concat([for (i in 16 ... (16 > 16 ? 16 : 16 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_internalexample.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing_internalexample.InternalExample>);
function main():Void {
    var _m = stdgo._internal.testing.Testing_mainstart.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps_testdeps.TestDeps), _internal.gotype.Gotype___type__stdgodot_internaldottestingdotinternaldottestdepsdottestdeps_testdepsdottestdeps.__type__stdgodot_internaldottestingdotinternaldottestdepsdotTestdeps_testdepsdotTestDeps), _tests, _benchmarks, _fuzzTargets, _examples);
    //"file:///Users/o/Library/Caches/go-build/08/08135f0f9438189f1790bae1119f4b6dc210a6ad72eca1bd65e32dfe98b5ad99-d#L149"
    #if (sys || hxnodejs) Sys.exit(_m.run()) #else null #end;
}
@:keep var __init_go2hx__ = {
    try {
        var __tmp__0 = _internal.unicode.utf8dottest.Utf8dottest._tests, __tmp__1 = _internal.unicode.utf8dottest.Utf8dottest._benchmarks, __tmp__2 = _internal.unicode.utf8dottest.Utf8dottest._fuzzTargets, __tmp__3 = _internal.unicode.utf8dottest.Utf8dottest._examples;
        stdgo._internal.testing.internal.testdeps.Testdeps_importpath.importPath = ("unicode/utf8" : stdgo.GoString);
    } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
    true;
};
