package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_30pointerpointer_static_extension.T__struct_30PointerPointer_static_extension) typedef T__struct_30PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_30pointerpointer.T__struct_30PointerPointer>;
