package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_16pointerpointer_static_extension.T__struct_16PointerPointer_static_extension) typedef T__struct_16PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_16pointerpointer.T__struct_16PointerPointer>;
