package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_23pointerpointer_static_extension.T__struct_23PointerPointer_static_extension) typedef T__struct_23PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_23pointerpointer.T__struct_23PointerPointer>;
