package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_152pointerpointer_static_extension.T__struct_152PointerPointer_static_extension) typedef T__struct_152PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_152pointerpointer.T__struct_152PointerPointer>;
