package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_6pointerpointer_static_extension.T__struct_6PointerPointer_static_extension) typedef T__struct_6PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_6pointerpointer.T__struct_6PointerPointer>;
