package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_33pointerpointer_static_extension.T__struct_33PointerPointer_static_extension) typedef T__struct_33PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_33pointerpointer.T__struct_33PointerPointer>;
