package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_151pointerpointer_static_extension.T__struct_151PointerPointer_static_extension) typedef T__struct_151PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_151pointerpointer.T__struct_151PointerPointer>;
