package _internal.bytes_test;
@:keep @:allow(_internal.bytes_test.Bytes_test.T_testReaderCopyNothing___localname___nErr_5822Pointer_asInterface) class T_testReaderCopyNothing___localname___nErr_5822Pointer_static_extension {

}
