package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_15pointerpointer_static_extension.T__struct_15PointerPointer_static_extension) typedef T__struct_15PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_15pointerpointer.T__struct_15PointerPointer>;
