package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_150pointerpointer_static_extension.T__struct_150PointerPointer_static_extension) typedef T__struct_150PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_150pointerpointer.T__struct_150PointerPointer>;
