package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_29pointerpointer_static_extension.T__struct_29PointerPointer_static_extension) typedef T__struct_29PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_29pointerpointer.T__struct_29PointerPointer>;
