package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_2pointerpointer_static_extension.T__struct_2PointerPointer_static_extension) typedef T__struct_2PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_2pointerpointer.T__struct_2PointerPointer>;
