package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_22pointerpointer_static_extension.T__struct_22PointerPointer_static_extension) typedef T__struct_22PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_22pointerpointer.T__struct_22PointerPointer>;
