package _internal.bytes_test;
var _indexFuncTests : stdgo.Slice<_internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest> = (new stdgo.Slice<_internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest>(16, 16, ...[
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str() : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__isvalidrune._isValidRune?.__copy__(), (-1 : stdgo.GoInt), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest(("abc" : stdgo.GoString), _internal.bytes_test.Bytes_test__isdigit._isDigit?.__copy__(), (-1 : stdgo.GoInt), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest(("0123" : stdgo.GoString), _internal.bytes_test.Bytes_test__isdigit._isDigit?.__copy__(), (0 : stdgo.GoInt), (3 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest(("a1b" : stdgo.GoString), _internal.bytes_test.Bytes_test__isdigit._isDigit?.__copy__(), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest(("\t\x0B\r\x0C\n\u0085\u00a0\u2000\u3000" : stdgo.GoString), _internal.bytes_test.Bytes_test__isspace._isSpace?.__copy__(), (0 : stdgo.GoInt), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest(("๐๒12hello34๐๑" : stdgo.GoString), _internal.bytes_test.Bytes_test__isdigit._isDigit?.__copy__(), (0 : stdgo.GoInt), (18 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest(("ⱯⱯⱯⱯABCDhelloEFⱯⱯGHⱯⱯ" : stdgo.GoString), _internal.bytes_test.Bytes_test__isupper._isUpper?.__copy__(), (0 : stdgo.GoInt), (34 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest(("12๐๒hello34๐๑" : stdgo.GoString), _internal.bytes_test.Bytes_test__not._not(_internal.bytes_test.Bytes_test__isdigit._isDigit?.__copy__())?.__copy__(), (8 : stdgo.GoInt), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str(128, "1") : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__isdigit._isDigit?.__copy__(), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str(128, "abc") : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__isdigit._isDigit?.__copy__(), (-1 : stdgo.GoInt), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str(192, "a", 192) : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__isvalidrune._isValidRune?.__copy__(), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str(192, "a", 192) : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__not._not(_internal.bytes_test.Bytes_test__isvalidrune._isValidRune?.__copy__())?.__copy__(), (0 : stdgo.GoInt), (2 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str(192, "☺", 192) : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__not._not(_internal.bytes_test.Bytes_test__isvalidrune._isValidRune?.__copy__())?.__copy__(), (0 : stdgo.GoInt), (4 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str(192, "☺", 192, 192) : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__not._not(_internal.bytes_test.Bytes_test__isvalidrune._isValidRune?.__copy__())?.__copy__(), (0 : stdgo.GoInt), (5 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str("ab", 192, "a", 192, "cd") : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__not._not(_internal.bytes_test.Bytes_test__isvalidrune._isValidRune?.__copy__())?.__copy__(), (2 : stdgo.GoInt), (4 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest),
(new _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest((stdgo.Go.str("a", 224, 128, "cd") : stdgo.GoString)?.__copy__(), _internal.bytes_test.Bytes_test__not._not(_internal.bytes_test.Bytes_test__isvalidrune._isValidRune?.__copy__())?.__copy__(), (1 : stdgo.GoInt), (2 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest)].concat([for (i in 16 ... (16 > 16 ? 16 : 16 : stdgo.GoInt).toBasic()) ({} : _internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest)])) : stdgo.Slice<_internal.bytes_test.Bytes_test_indexfunctest.IndexFuncTest>);
