package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_158pointerpointer_static_extension.T__struct_158PointerPointer_static_extension) typedef T__struct_158PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_158pointerpointer.T__struct_158PointerPointer>;
