package _internal.bytes_test;
@:keep @:follow @:using(_internal.bytes_test.Bytes_test_t__struct_162pointerpointer_static_extension.T__struct_162PointerPointer_static_extension) typedef T__struct_162PointerPointerPointer = stdgo.Pointer<_internal.bytes_test.Bytes_test_t__struct_162pointerpointer.T__struct_162PointerPointer>;
