package stdgo._internal.encoding.asn1;
import stdgo._internal.math.big.Big;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.time.Time;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.errors.Errors;
import stdgo._internal.unicode.utf16.Utf16;
import stdgo._internal.strings.Strings;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.sort.Sort;
import stdgo._internal.bytes.Bytes;
var _byteFFEncoder : stdgo._internal.encoding.asn1.Asn1_t_encoder.T_encoder = stdgo.Go.asInterface((255 : stdgo._internal.encoding.asn1.Asn1_t_byteencoder.T_byteEncoder), _internal.gotype.Gotype___type__stdgodot_internaldotencodingdotasn1dotasn1_t_byteencoderdott_byteencoder.__type__stdgodot_internaldotencodingdotasn1dotAsn1_t_byteencoderdotT_byteEncoder);
