package stdgo._internal.math.big;
import stdgo._internal.errors.Errors;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.math.rand.Rand;
var _threeOnce : stdgo._internal.math.big.Big_t__struct_32.T__struct_32 = ({ once : ({} : stdgo._internal.sync.Sync_once.Once), _v : (null : stdgo.Ref<stdgo._internal.math.big.Big_float_.Float_>) } : stdgo._internal.math.big.Big_t__struct_32.T__struct_32);
