package stdgo._internal.math.big;
import stdgo._internal.errors.Errors;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.math.rand.Rand;
@:keep @:follow @:using(stdgo._internal.math.big.Big_float__static_extension.Float__static_extension) @:using(stdgo._internal.math.big.Big_float_pointer_static_extension.Float_Pointer_static_extension) typedef Float_Pointer = stdgo.Pointer<stdgo._internal.math.big.Big_float_.Float_>;
