package stdgo._internal.math.big;
import stdgo._internal.errors.Errors;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.math.rand.Rand;
var __6 : stdgo._internal.fmt.Fmt_scanner.Scanner = stdgo.Go.asInterface((stdgo.Go.setRef(stdgo._internal.math.big.Big__ratzero._ratZero, stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotmathdotbigdotbig_ratdotrat.__type__stdgodot_internaldotmathdotbigdotBig_ratdotRat })) : stdgo.Ref<stdgo._internal.math.big.Big_rat.Rat>), stdgo._internal.internal.reflect.GoType.refType({ get : () -> _internal.gotype.Gotype___type__stdgodot_internaldotmathdotbigdotbig_ratdotrat.__type__stdgodot_internaldotmathdotbigdotBig_ratdotRat }));
