package stdgo._internal.math.big;
import stdgo._internal.errors.Errors;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.math.rand.Rand;
@:keep @:follow @:using(stdgo._internal.math.big.Big_t_nat_static_extension.T_nat_static_extension) @:using(stdgo._internal.math.big.Big_t_natpointer_static_extension.T_natPointer_static_extension) typedef T_natPointer = stdgo.Pointer<stdgo._internal.math.big.Big_t_nat.T_nat>;
