package stdgo._internal.math.big;
import stdgo._internal.errors.Errors;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.math.rand.Rand;
@:named @:using(stdgo._internal.math.big.Big_word_static_extension.Word_static_extension) @:using(stdgo._internal.math.big.Big_word_static_extension.Word_static_extension) typedef Word = stdgo.GoUInt;
