package stdgo._internal.internal.nettrace;
@:keep @:follow @:using(stdgo._internal.internal.nettrace.Nettrace_lookupipaltresolverkeypointer_static_extension.LookupIPAltResolverKeyPointer_static_extension) typedef LookupIPAltResolverKeyPointerPointer = stdgo.Pointer<stdgo._internal.internal.nettrace.Nettrace_lookupipaltresolverkeypointer.LookupIPAltResolverKeyPointer>;
