package _internal.context_test;
@:keep @:follow @:using(_internal.context_test.Context_test_t_afterfunccontextpointer_static_extension.T_afterFuncContextPointer_static_extension) typedef T_afterFuncContextPointerPointer = stdgo.Pointer<_internal.context_test.Context_test_t_afterfunccontextpointer.T_afterFuncContextPointer>;
