package _internal.context_test;
@:keep @:follow @:using(_internal.context_test.Context_test_t__struct_19pointerpointer_static_extension.T__struct_19PointerPointer_static_extension) typedef T__struct_19PointerPointerPointer = stdgo.Pointer<_internal.context_test.Context_test_t__struct_19pointerpointer.T__struct_19PointerPointer>;
