package _internal.context_test;
@:keep @:follow @:using(_internal.context_test.Context_test_t__struct_18pointerpointer_static_extension.T__struct_18PointerPointer_static_extension) typedef T__struct_18PointerPointerPointer = stdgo.Pointer<_internal.context_test.Context_test_t__struct_18pointerpointer.T__struct_18PointerPointer>;
