package _internal.context_test;
@:keep @:follow @:using(_internal.context_test.Context_test_t_othercontextpointer_static_extension.T_otherContextPointer_static_extension) typedef T_otherContextPointerPointer = stdgo.Pointer<_internal.context_test.Context_test_t_othercontextpointer.T_otherContextPointer>;
