package _internal.context_test;
@:keep @:follow @:using(_internal.context_test.Context_test_t__struct_17pointerpointer_static_extension.T__struct_17PointerPointer_static_extension) typedef T__struct_17PointerPointerPointer = stdgo.Pointer<_internal.context_test.Context_test_t__struct_17pointerpointer.T__struct_17PointerPointer>;
