package _internal.context_test;
@:keep @:follow @:using(_internal.context_test.Context_test_t__struct_24pointerpointer_static_extension.T__struct_24PointerPointer_static_extension) typedef T__struct_24PointerPointerPointer = stdgo.Pointer<_internal.context_test.Context_test_t__struct_24pointerpointer.T__struct_24PointerPointer>;
