package _internal.context_test;
@:keep @:follow @:using(_internal.context_test.Context_test_t_customdonecontextpointer_static_extension.T_customDoneContextPointer_static_extension) typedef T_customDoneContextPointerPointer = stdgo.Pointer<_internal.context_test.Context_test_t_customdonecontextpointer.T_customDoneContextPointer>;
