package _internal.githubdotcom.dlclark.regexp2;
import stdgo._internal.regexp.Regexp;
import stdgo._internal.time.Time;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.log.Log;
import _internal.githubdotcom.dlclark.regexp2.syntax.Syntax;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.os.Os;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.strings.Strings;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.encoding.json.Json;
import stdgo._internal.errors.Errors;
import stdgo._internal.sync.atomic_.Atomic_;
import stdgo._internal.unicode.Unicode;
@:keep @:follow @:using(_internal.githubdotcom.dlclark.regexp2.Regexp2_t__struct_53pointer_static_extension.T__struct_53Pointer_static_extension) @:using(_internal.githubdotcom.dlclark.regexp2.Regexp2_t__struct_53pointerpointer_static_extension.T__struct_53PointerPointer_static_extension) typedef T__struct_53PointerPointer = stdgo.Pointer<_internal.githubdotcom.dlclark.regexp2.Regexp2_t__struct_53pointer.T__struct_53Pointer>;
