package _internal.unicode.utf8_test;
@:keep @:follow @:using(_internal.unicode.utf8_test.Utf8_test_t__struct_14pointerpointer_static_extension.T__struct_14PointerPointer_static_extension) typedef T__struct_14PointerPointerPointer = stdgo.Pointer<_internal.unicode.utf8_test.Utf8_test_t__struct_14pointerpointer.T__struct_14PointerPointer>;
