package stdgo._internal.reflect;
@:keep @:follow @:using(stdgo._internal.reflect.Reflect_t_visiblefieldswalkerpointer_static_extension.T_visibleFieldsWalkerPointer_static_extension) typedef T_visibleFieldsWalkerPointerPointer = stdgo.Pointer<stdgo._internal.reflect.Reflect_t_visiblefieldswalkerpointer.T_visibleFieldsWalkerPointer>;
