package stdgo._internal.reflect;
@:keep @:follow @:using(stdgo._internal.reflect.Reflect_t_structtypeuncommonpointer_static_extension.T_structTypeUncommonPointer_static_extension) typedef T_structTypeUncommonPointerPointer = stdgo.Pointer<stdgo._internal.reflect.Reflect_t_structtypeuncommonpointer.T_structTypeUncommonPointer>;
