package stdgo._internal.crypto.internal.edwards25519;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.errors.Errors;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.crypto.subtle.Subtle;
@:keep @:follow @:using(stdgo._internal.crypto.internal.edwards25519.Edwards25519_t_fiatscalarnonmontgomerydomainfieldelementpointer_static_extension.T_fiatScalarNonMontgomeryDomainFieldElementPointer_static_extension) typedef T_fiatScalarNonMontgomeryDomainFieldElementPointerPointer = stdgo.Pointer<stdgo._internal.crypto.internal.edwards25519.Edwards25519_t_fiatscalarnonmontgomerydomainfieldelementpointer.T_fiatScalarNonMontgomeryDomainFieldElementPointer>;
